### ISSUE TITLE
Build failure due to not correctly determining getpwnam_r

### ISSUE THREAD

**Issue by quanah** [cyrusimap/cyrus-sasl#11]
Building cyrus-sasl HEAD linking to the latest Heimdal 7.0.1 results in:

```
<command-line>:0:0: note: this is the location of the previous definition
auth_shadow.c: In function 'auth_shadow':
auth_shadow.c:151:5: error: too few arguments to function 'getpwnam_r'
     pw = getpwnam_r(login, &pwbuf, pwdata, sizeof(pwdata));
     ^
In file included from auth_shadow.c:49:0:
/usr/include/pwd.h:150:12: note: declared here
 extern int getpwnam_r (const char *__restrict __name,
            ^
auth_shadow.c:185:5: error: too few arguments to function 'getspnam_r'
     sp = getspnam_r(login, &spbuf, spdata, sizeof(spdata));
     ^
In file included from auth_shadow.c:73:0:
/usr/include/shadow.h:123:12: note: declared here
 extern int getspnam_r (const char *__name, struct spwd *__result_buf,
            ^
```

**Comment by quanah** [comment]
Note: Building on CentOS 7

**Comment by quanah** [comment]
Root problem appears to be that GETXXNAM_R_5ARG in config.h or anywhere else,  which causes the wrong form to be used on systems where it takes 5 ARGS

**Comment by quanah** [comment]
Putting -DGETXXNAM_R_5ARG in my CFLAGS allowed the build to proceed.  This definitely needs to be part of a configure check though.

**Comment by ksmurchison** [comment]
Can you try this patch?  Looks like this test was lost when we removed saslauthd/configure.in

[configure.5arg.diff.txt](https://github.com/cyrusimap/cyrus-sasl/files/643209/configure.5arg.diff.txt)

**Comment by quanah** [comment]
Worked with this patch applied, thanks.

**Comment by ksmurchison** [comment]
Fixed with https://github.com/cyrusimap/cyrus-sasl/commit/400e0feb2e3acddb1c5677b75ef627861614f160
