### ISSUE TITLE
KRB5_HEIMDAL declared twice, creates tons of compiler warnings

### ISSUE THREAD

**Issue by quanah** [cyrusimap/cyrus-sasl#12]
KRB5_HEIMDAL is defined both in config.h and as a -D parameter passed to make, causing the build process to constantly spew warnings that KRB5_HEIMDAL was already defined.

**Comment by ksmurchison** [comment]
This is a complete shot in the dark.  Can you test this patch?

[sasl2.m4.heimdal.diff.txt](https://github.com/cyrusimap/cyrus-sasl/files/643212/sasl2.m4.heimdal.diff.txt)

**Comment by quanah** [comment]
Success, thanks!

**Comment by ksmurchison** [comment]
Fixed with https://github.com/cyrusimap/cyrus-sasl/commit/b4aaa9e197d36028212e527d55a801e5ab13883a
