### ISSUE TITLE
Security factor for SASL/GSSAPI hard coded to "56"

### ISSUE THREAD

**Issue by quanah** [cyrusimap/cyrus-sasl#13]
A long time frustration with cyrus-sasl is that it hard codes the security factor for GSSAPI to be 56, rather than a security factor based off the cipher etc negotiated.  It would be extremely useful to have usable security factors reported by cyrus-sasl when SASL/GSSAPI is being used.

Example of hard coding:

```
./plugins/gssapi.c:#define K5_MAX_SSF   56
```

**Comment by NWilson** [comment]
Dupe of prior issue https://github.com/cyrusimap/cyrus-sasl/issues/191

**Comment by ksmurchison** [comment]
Fixed with https://github.com/cyrusimap/cyrus-sasl/commit/d6fbfd7bb2888fb12eb36f1523bcce8bbb420a24
