### ISSUE TITLE
des support in openssl libcrypto not found

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-sasl#155]
From: [Carsten Ehlers](calle@toppoint.de)
Bugzilla-Id: 1593
Version: 2.1.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by quanah** [comment]
Closing, ancient and likely fixed.  Feel free to re-open if it can be reproduced (I've never seen it with custom ssl installation locations)
