### ISSUE TITLE
GSSAPI doesn't return the proper SSF when 3DES and/or AES is available

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-sasl#191]
From: [Alexey Melnikov](Alexey.Melnikov@isode.com)
Bugzilla-Id: 2244
Version: 2.1.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by ksmurchison** [comment]
Fixed with https://github.com/cyrusimap/cyrus-sasl/commit/ff9f9caeb6db6d7513128fff9321f9bd445f58b7
