### ISSUE TITLE
the opaque pointer type is "int" in JNI layer

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-sasl#25]
From: [Larry Greenfield](leg+cyrus@andrew.cmu.edu)
Bugzilla-Id: 412
Version: 2.1.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by cthpw103** [comment]
really hope they fix this issue

**Comment by quanah** [comment]
java layer removed as it was unmaintained and unusable.
