### ISSUE TITLE
login client plugin calls for the password before it needs it

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-sasl#291]
From: [Ian Anderson](iana@apple.com)
Bugzilla-Id: 3239
Version: 2.1.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by ksmurchison** [comment]
Fixed with https://github.com/cyrusimap/cyrus-sasl/commit/9bb0bb030d3df3bc7dab698294898540c2abc91b
