### ISSUE TITLE
sql format syntax doesn't differentiate NULL values

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-sasl#296]
From: [Fabian Fagerholm](fabbe@paniq.net)
Bugzilla-Id: 3039
Version: 2.1.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by bgermann** [comment]
Is this fixed by 2d2e97b0eb53fa7f87a3bf1529d8f712dd954480?

**Comment by quanah** [comment]
@hyc Is this fixed in 2.1.28 with the sql escaping fix?

**Comment by hyc** [comment]
Yes, this is pretty much the same fix, closing this.
