### ISSUE TITLE
saslauthd: configuration option for LDAP_OPT_TIMEOUT in addition to LDAP_OPT_NETWORK_TIMEOUT

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-sasl#310]
From: [Kazuo Ito](ito.kazuo@oss.ntt.co.jp)
Bugzilla-Id: 3125
Version: 2.1.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by quanah** [comment]
This was already fixed in 6b2dddb7
