### ISSUE TITLE
bug in "saslauthd -a rimap"

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-sasl#323]
From: [Lutz](lutz.mark@ifam.fraunhofer.de)
Bugzilla-Id: 3209
Version: 2.1.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by ksmurchison** [comment]
Fixed with https://github.com/cyrusimap/cyrus-sasl/commit/2d0e416946ee599e407fca9ab0858a1ebe27cd80
