### ISSUE TITLE
compiling cyrus-sasl with db50

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-sasl#330]
From: [Hajimu UMEMOTO](ume@mahoroba.org)
Bugzilla-Id: 3230
Version: 2.1.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by ksmurchison** [comment]
Fixed with https://github.com/cyrusimap/cyrus-sasl/commit/417b32dfbed13bc0ede81c05671eedf7874c44d9
