### ISSUE TITLE
SASL should use pthread_mutex where available

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-sasl#331]
From: [Ian Anderson](iana@apple.com)
Bugzilla-Id: 3232
Version: 2.1.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by hyc** [comment]
Strange that this bug was filed in 2010 since it was already fixed in 2008, 4b1f70860a873b47645c64e6b7f0d0ed5edb95c5

**Comment by quanah** [comment]
Side note: The 2010 date is when this issue was imported from the old bugzilla, not when it was created.  The actual creation dates were not preserved as a part of that migration.
