### ISSUE TITLE
NTLM should make the v1/v2 determination on its own

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-sasl#332]
From: [Ian Anderson](iana@apple.com)
Bugzilla-Id: 3233
Version: 2.1.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by ksmurchison** [comment]
Per https://msdn.microsoft.com/en-us/library/cc236700.aspx, v1/v2 is NOT negotiated by the protocol and MUST be configured on client and server
