### ISSUE TITLE
adding some sha mechanisms

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-sasl#336]
From: david.maciejak@gmail.com
Bugzilla-Id: 3373
Version: 2.1.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by brong** [comment]
Closing: was RESOLVED in import

**Comment by Neustradamus** [comment]
Any news for other points?
- https://github.com/cyrusimap/cyrus-sasl/issues/552

It is easy to add -PLUS part?
