### ISSUE TITLE
Cyrus-sasl defaults to using /dev/random instead of /dev/urandom

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-sasl#361]
From: [Quanah Gibson-Mount](quanah@zimbra.com)
Bugzilla-Id: 3592
Version: 2.1.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by ksmurchison** [comment]
This is configurable and compile-time

**Comment by quanah** [comment]
@ksmurchison The point was that the default is problematic, not that it isn't configurable.

**Comment by ksmurchison** [comment]
Fixed with https://github.com/cyrusimap/cyrus-sasl/commit/e924cc9c895f2d6a74153fac83b223a5d465f8e2
