### ISSUE TITLE
Java JNDI Client Connects to OpenLDAP fail

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-sasl#378]
From: [Bill MacAllister](whm@stanford.edu)
Bugzilla-Id: 3787
Version: 2.1.25
Owner: [Alexey Melnikov](Alexey.Melnikov@isode.com)

**Comment by quanah** [comment]
This might be the same as issue #419 

As I recall when I worked @ Stanford, JNDI defaults to having an SSF of 0.  It was one of the reasons we dumped JNDI for UnboundID.  I'm surprised anyone @ Stanford was continuing to use JNDI given its many flaws.

**Comment by quanah** [comment]
@whm this is you IIRC. ;)

**Comment by whitehse** [comment]
@whm

Issue #419 has been resolved in 2.1.27 rc6. Can you retest this, or provide instructions for reproducing your test?

**Comment by quanah** [comment]
@whm no longer works at Stanford, and may not have any ability to test this.  I still have connections at Stanford, so I can see if any of them can test this.

**Comment by quanah** [comment]
Going to close this, I believe this is fixed with #419 being resolved.

If someone continues to have this issue, please reopen.
