### ISSUE TITLE
Why is PLAIN prefered over SCRAM-SHA-1?

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-sasl#379]
From: [Thijs Alkemade](me@thijsalkema.de)
Bugzilla-Id: 3793
Version: 2.1.25
Owner: [Alexey Melnikov](Alexey.Melnikov@isode.com)

**Comment by ksmurchison** [comment]
Hopefully fixed by https://github.com/cyrusimap/cyrus-sasl/commit/37ab5a81052c6086f47ec9def63899be40a08bad

**Comment by Neustradamus** [comment]
There is a problem of priority for SCRAM-SHA-256 and SCRAM-SHA-1.
- https://github.com/cyrusimap/cyrus-sasl/pull/577

Any news for add other too?
- https://github.com/cyrusimap/cyrus-sasl/issues/552

It is easy to add -PLUS part?
