### ISSUE TITLE
[PATCH] Allow "* CAPABILITY" lines in IMAP login reply

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-sasl#381]
From: [Sebastian Pipping](sebastian@pipping.org)
Bugzilla-Id: 3802
Version: 2.1.x
Owner: [Alexey Melnikov](Alexey.Melnikov@isode.com)

**Comment by ksmurchison** [comment]
Which server returns an unsolicited CAPABILITY response during execution of LOGIN command?  I know that Cyrus IMAP uses a CAPABILITY response code in the tagged response

**Comment by quanah** [comment]
Dovecot does this, as per the original bug report filed with Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=715040
