### ISSUE TITLE
Libsasl spams our logs with "DIGEST-MD5 common mech free" messages

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-sasl#386]
From: [Sjon](sjon@parse.nl)
Bugzilla-Id: 3818
Version: 2.1.x
Owner: [Alexey Melnikov](Alexey.Melnikov@isode.com)

**Comment by ksmurchison** [comment]
This is now logged as DEBUG level

**Comment by Lekensteyn** [comment]
Is there a reason to keep the log message? With modern Linux distributions, journald is configured to log all messages, including debug. There does not seem to be a way to ignore this message with some other environment variable.

Please consider removing it as it makes using subversion very noisy.

**Comment by athos-ribeiro** [comment]
Any news on this one regarding the comment above (https://github.com/cyrusimap/cyrus-sasl/issues/386#issuecomment-504710968)?

It seems this log message is indeed logged quite often to the journal on systems running systemd.
