### ISSUE TITLE
Building from git repository fails (1. no cmulocal directory; 2. make error @GSSAPI_LIBS@)

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-sasl#389]
From: [Mimiko](vbvbrj@gmail.com)
Bugzilla-Id: 3842
Version: 2.1.x
Owner: [Alexey Melnikov](Alexey.Melnikov@isode.com)

**Comment by ksmurchison** [comment]
Fixed with update to newer autoconf tools
