### ISSUE TITLE
You need to create libsasl2.pc from Makefile.am and not configure.in for proper (expanded) substitions

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-sasl#392]
From: [Ondrej Sury](ondrej@sury.org)
Bugzilla-Id: 3857
Version: 2.1.x
Owner: [Alexey Melnikov](Alexey.Melnikov@isode.com)

**Comment by dilyanpalauzov** [comment]
This was fixed with commit 3f42b7d7f3ef5205 . `${prefix}` is now defined in `libsasl2.pc`.
