### ISSUE TITLE
cyrus_sasl 2.1.26 pkgconfig is broken

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-sasl#398]
From: [Domen Ko&#158;ar](domen@dev.si)
Bugzilla-Id: 3891
Version: 2.1.25
Owner: [Alexey Melnikov](Alexey.Melnikov@isode.com)

**Comment by ksmurchison** [comment]
Should be fixed with commit 3f42b7d7f3ef52056c79b31529d1a5be695c74c1
