### ISSUE TITLE
auxprop SQL plugin creates auth.debug log messages despite log_level set to 0

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-sasl#401]
From: [Patrick Wagner](patrick.wagner@rga-net.de)
Bugzilla-Id: 3906
Version: 2.1.x
Owner: [Alexey Melnikov](Alexey.Melnikov@isode.com)

**Comment by ksmurchison** [comment]
Fixed with https://github.com/cyrusimap/cyrus-sasl/commit/dfcbce9490199a82a75c3a2a591be4ae690b4395
