### ISSUE TITLE
SASL GSSAPI mechanism acceptor wrongly returns zero maxbufsize

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-sasl#402]
From: [Sergio Gelato](Sergio.Gelato@astro.su.se)
Bugzilla-Id: 3912
Version: 2.1.x
Owner: [Alexey Melnikov](Alexey.Melnikov@isode.com)

**Comment by whm** [comment]
I started seeing this problem on my Xenial OpenLDAP server last night.  The error was:

slapd[22083]: encoded packet size too big (67871 > 65536)

Applying this patch to the Xenial build of Cyrus SASL has resolved the issue.  The exact version is: 2.1.26.dfsg1-14build1.

**Comment by tobyblake** [comment]
Hello, just a me-too to say that we saw this issue with machines upgraded to Scientific Linux 7 (from SL6) and the patch included here does seem to fix the issue for us.  It would be good if it could be included in the next release.

**Comment by ksmurchison** [comment]
Fixed with https://github.com/cyrusimap/cyrus-sasl/commit/6f8cc363ffa41958ccf08eaf6754690f89e3af03
