### ISSUE TITLE
Rename mdb backend to lmdb and add support for windows

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-sasl#403]
From: [Ignacio Casal Quinteiro](nacho.resa@gmail.com)
Bugzilla-Id: 3913
Version: 2.1.x
Owner: [Alexey Melnikov](Alexey.Melnikov@isode.com)

**Comment by ksmurchison** [comment]
Fixed with https://github.com/cyrusimap/cyrus-sasl/commit/3ea310f668e80ce12587c993808ba0d5446bc4e5
