### ISSUE TITLE
libsasl2.so.3: cannot open shared object file:

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-sasl#406]
From: [Christian Watt](cwatt@phacil.com)
Bugzilla-Id: 3917
Version: 2.1.x
Owner: [Alexey Melnikov](Alexey.Melnikov@isode.com)

**Comment by ralphtheninja** [comment]
Not a single person responded to this?

**Comment by quanah** [comment]
Sounds to me like imtest was compiled without the correct RPATH.  One would want the output of something like ldd or readelf -d to pursue this any further.
