### ISSUE TITLE
Trivial string termination bug in testsuite.c

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-sasl#414]
From: [Jan Parcel](jan.parcel@oracle.com)
Bugzilla-Id: 3935
Version: 2.1.x
Owner: [Alexey Melnikov](Alexey.Melnikov@isode.com)

**Comment by ksmurchison** [comment]
Fixed with https://github.com/cyrusimap/cyrus-sasl/commit/dc1e731ac07f6034cfc60801c5495686ca9572c0
