### ISSUE TITLE
We have man pages to contribute upstream

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-sasl#415]
From: [Jan Parcel](jan.parcel@oracle.com)
Bugzilla-Id: 3936
Version: 2.1.x
Owner: [Alexey Melnikov](Alexey.Melnikov@isode.com)

**Comment by nicolan** [comment]
I've contacted Jan Parcel to ask for the man pages.

**Comment by nicolan** [comment]
Fixed in PR #458
