### ISSUE TITLE
crash in NTLM plugin

### ISSUE THREAD

**Issue by stalra** [cyrusimap/cyrus-sasl#417]
There is a missing initialization in the NTLM plugin that leads to crashes during login (at least on Solaris). The corresponding openssl man page states:

HMAC_CTX_init() initialises a HMAC_CTX before first use. It must be called.

Here is the proposed patch: [ntlm-patch.txt](https://github.com/cyrusimap/cyrus-sasl/files/719003/ntlm-patch.txt)

**Comment by Jakuje** [comment]
Please, fill a pull request so it will not get lost and will get covered in the next release.

**Comment by ksmurchison** [comment]
Fixed with https://github.com/cyrusimap/cyrus-sasl/commit/0aaa7bea444f5a660e8061bd676ff2a1ddfaa459
