### ISSUE TITLE
HEAD of master branch fails to build on Solaris 11.3

### ISSUE THREAD

**Issue by makr** [cyrusimap/cyrus-sasl#425]
Hi everybody,

the current HEAD of the master branch fails to build on Solaris 11.3. It doesn't matter if Oracle Developer Studio 12.5 is used as compiler or the GNU Development Tools (which is based on a GCC 4.8). It also fails on the SPARC and the AMD64 architecture.

The final lines of the build are:
```
makr@sun2:~/sun2/cyrus-sasl-2.1.27-GIT$ (PATH="`getconf PATH`" ./configure; gmake)
[… skipping to the last few lines …]
source='../plugins/plugin_common.c' object='../plugins/plugin_common.lo' libtool=yes \
DEPDIR=.deps depmode=none /bin/sh ../config/depcomp \
/bin/sh ../libtool  --tag=CC   --mode=compile cc -DHAVE_CONFIG_H -I. -I..  -DLIBSASL_EXPORTS=1 -I../include -I../plugins -I../include -I../sasldb -DOBSOLETE_CRAM_ATTR=1  -g -c -o ../plugins/plugin_common.lo ../plugins/plugin_common.c
libtool: compile:  cc -DHAVE_CONFIG_H -I. -I.. -DLIBSASL_EXPORTS=1 -I../include -I../plugins -I../include -I../sasldb -DOBSOLETE_CRAM_ATTR=1 -g -c ../plugins/plugin_common.c  -KPIC -DPIC -o ../plugins/.libs/plugin_common.o
/bin/sh ../libtool  --tag=CC   --mode=link cc  -g   -o libobj.la    -lresolv -lresolv   -lsocket
libtool: link: ar cru .libs/libobj.a
libtool: link: ranlib .libs/libobj.a
libtool: link: ( cd ".libs" && rm -f "libobj.la" && ln -s "../libobj.la" "libobj.la" )
/bin/sh ../libtool  --tag=CC   --mode=link cc  -g -version-info 3:0:0 -no-undefined  -o libsasl2.la -rpath /usr/local/lib auxprop.lo canonusr.lo checkpw.lo client.lo common.lo config.lo external.lo md5.lo saslutil.lo server.lo seterror.lo dlopen.lo ../plugins/plugin_common.lo  libobj.la -ldl -lsocket -lnsl -lsocket  -lresolv -lresolv   -lsocket
libtool: link: cc -G -z defs -h libsasl2.so.3 -o .libs/libsasl2.so.3.0.0  .libs/auxprop.o .libs/canonusr.o .libs/checkpw.o .libs/client.o .libs/common.o .libs/config.o .libs/external.o .libs/md5.o .libs/saslutil.o .libs/server.o .libs/seterror.o .libs/dlopen.o ../plugins/.libs/plugin_common.o  -z allextract ./.libs/libobj.a -z defaultextract  -ldl -lnsl -lresolv -lsocket -lc
ld: fatal: file ./.libs/libobj.a: open failed: No such file or directory
gmake[3]: *** [libsasl2.la] Error 2
gmake[3]: Leaving directory `/path/to/sun2/cyrus-sasl-2.1.27-GIT/lib'
```
As Stefan Rapp explained in the mailing list, the reason is that the Solaris' **`ar`** tool will not create empty archives. Hence `libobj.a` is not created.

The autotools stuff should be able to somehow cope with this behavior.

As a workaround **`ar`** can be instructed to generate empty archives when the flag **`-s`** is added to force creating a symbol table. As far as I can see, however, this is undocumented behavior. So the following command line will currently work around this issue:
`./configure ... AR_FLAGS=crus`

Kind regards
-- Matthias Kraft

**Comment by ksmurchison** [comment]
Do you have a proposed patch to configure.ac for this?

**Comment by makr** [comment]
Sorry I am currently on vacation and don't have access to my sources. A proper answer will have to wait until end of July. On the other hand, if I would have seen an obvious fix I would have included it in my report or comment. 
-- 
Matthias Kraft
-----------------
sent with R2Mail2

---- Von: Ken Murchison <notifications@github.com> -- Gesendet: 2017-07-13 - 16:00 ----

**Comment by quanah** [comment]
I am able to build cyrus-sasl on Solaris 11.3 for amd64 w/o issue using GCC.  It does require using the GNU version of ar (which is an available package in Solaris).  The following allows me to build cyrus-sasl (and a number of other software):

```
 pkg install git bison automake autoconf groff flex texinfo gcc gdb gnu-make
export PATH=/usr/gnu/bin:/usr/perl5/bin:$PATH
```

**Comment by makr** [comment]
I have been looking into this again using the current GIT master HEAD. I can only reiterate what @quanah wrote. Once /usr/gnu/bin is in PATH before /usr/xpg4/bin, the linking issues disappear. How to wrap that up into a proper AC macro I don't know. My AC-fu is obviously hopelessly outdated, as everything I tried today went down in flames.
The standard AM_PROG_AR macro seems only to check whether or not there is an 'ar' tool available.

I am not quite sure how to go from here. For me it would be sufficient to know, that I have to have the GNU packages installed on Solaris and to have them in my PATH before the XPG4 stuff.

Kind regards
-- Matthias Kraft

BTW: I had to use GIT master HEAD as 2.1.27rc3 failed to compile because of missing headers...

**Comment by JanParcel** [comment]
I am using the Sun Studio Compiler but with gnu first in my path and with this option:
CONFIGURE_OPTIONS += --without-gnu-ld

Somehow, libtool is looking for libobjs.la (and finds it) instead of .a, and everything is happy.  But that is with 2.1.27rc3 on 11.next.

**Comment by ksmurchison** [comment]
Matthias, can you try compiling rc4 to make sure that the header issues have be resolved?

**Comment by makr** [comment]
I can already report that it works out on Solaris 11.3 (sparc). The build still fails on x86_64 architecture, but this so far seems to be related to the configuration of the machine. I hope to be able to get this straight tomorrow.

**Comment by makr** [comment]
@ksmurchison the header issue is gone. I compiled rc4 on AIX, HP-UX, Solaris and Linux today. My quick test through an OpenLDAP client suggest it works out - at least for me :-) ...

**Comment by ksmurchison** [comment]
Closing this issue as resolved.  Reopen if there are remaining issues
