### ISSUE TITLE
why does configure.ac define  ../sasldb/.libs/libsasldb.al ?

### ISSUE THREAD

**Issue by JanParcel** [cyrusimap/cyrus-sasl#466]
A line like the below appears to succeed in "plugins" but fail in "utils" if I try to build without obeying the stricture to build sasldb inside the full source tree.  Unfortunately, our build infrastructure requires that, because of how we treat 32-bit vs 64-bit files.  So I'm wondering what I can do to work around that.

cyrus-sasl-2.1.27/configure.ac:  SASL_DB_LIB="$SASL_DB_LIB ../sasldb/.libs/libsasldb.al"

Can someone tell me what files I need to copy to the $(bits) area I'm working in?

A "normal" build of cyrus-sasl does not mention libsasldb.al, not even if I truss it.

I am using Sun Studio, not gcc.
 
libtool: link: cc -m32 -xO4 -xchip=pentium -xregs=no%frameptr -m32 -o .libs/dbconverter-2 dbconverter-2.o ../sasldb/.libs/libsasldb.al  -L/usr/lib ../sasldb/.libs/libsasldb.a ../lib/.libs/libsasl2.so -ldl -ldoor -lscf -ldb-5.1 -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lresolv
ld: fatal: file ../sasldb/.libs/libsasldb.al: open failed: No such file or directory

I notice this in ltmain.sh:

# Some compilers have problems with a '.al' extension so
# convenience libraries should have the same extension an
# archive normally would.

But I cannot find evidence that the .al library was ever created.

**Comment by JanParcel** [comment]
>If I change this:  SASL_DB_LIB="$SASL_DB_LIB ../sasldb/.libs/libsasldb.al"
to this:  SASL_DB_LIB="$SASL_DB_LIB"

Then I get much further.  I can build utils and plugins, which otherwise fail.    But I'm failing in saslauthd, and trying to fix it in saslauthd's Makefile.am, but not succeeding.

**Comment by ksmurchison** [comment]
Jan,

Can you try the attached patch?
[auth_sasldb.diff.txt](https://github.com/cyrusimap/cyrus-sasl/files/1277449/auth_sasldb.diff.txt)

**Comment by JanParcel** [comment]
This is with cyrus-sasl-2.1.27-sig-rc3.tar.gz, should I be testing with something later?


/usr/bin/env RUBY_VERSION=2.1 /builds/jparcel/trunk-cyrus-27/tools/userland-unpack  cyrus-sasl-2.1.27.tar.gz
/usr/bin/touch /builds/jparcel/trunk-cyrus-27/components/cyrus-sasl/cyrus-sasl-2.1.27/.unpacked
/usr/bin/patch -d /builds/jparcel/trunk-cyrus-27/components/cyrus-sasl/cyrus-sasl-2.1.27 --strip=1 --backup --version-control=numbered < patches/009-sasldb.patch
patching file configure.ac
Hunk #1 FAILED at 609.
1 out of 1 hunk FAILED -- saving rejects to file configure.ac.rej
patching file saslauthd/Makefile.am
Hunk #1 FAILED at 5.
Hunk #2 FAILED at 20.
2 out of 2 hunks FAILED -- saving rejects to file saslauthd/Makefile.am.rej
gmake: *** [/builds/jparcel/trunk-cyrus-27/make-rules/prep.mk:44: /builds/jparcel/trunk-cyrus-27/components/cyrus-sasl/cyrus-sasl-2.1.27/.patched-009-sasldb.patch] Error 1


Here is what I'm using, it's similar but not identical, but it's for rc3:
[libsasldb-configure.patch.txt](https://github.com/cyrusimap/cyrus-sasl/files/1282636/libsasldb-configure.patch.txt)

**Comment by JanParcel** [comment]
I hand-changed your patch into a patch for 2.1.27rc3 and it worked great.  I'll use that for now.

**Comment by ksmurchison** [comment]
Great.  Can this issue be closed or is there something else we need to fix?

**Comment by ksmurchison** [comment]
Closing this as resolved.  Reopen is issue persists
