### ISSUE TITLE
./configure --help summary

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-sasl#473]
Print $dbpath in the summary and take into account that $SASL_MECHS always starts with a space. 

```diff
diff --git a/configure.ac b/configure.ac
--- a/configure.ac
+++ b/configure.ac
@@ -1612,8 +1612,9 @@ echo
 echo "$PACKAGE - $VERSION"
 echo
 echo "Prefix....................: $prefix"
-echo "Plugins...................: $SASL_MECHS"
+echo "Plugins...................:$SASL_MECHS"
 echo "saslauthd support.........: $with_saslauthd"
+echo "DB path...................: $dbpath"
 echo "Java Support:.............: $enable_java"
 if test "$enable_java" = yes; then
    echo "Java Base.................: $JAVA_INCLUDES"

```

**Comment by Jakuje** [comment]
Please, submit a pull request with the proposed change. It is much easier to review and accept them than from the issue with inline diff.

If you do not know how, github has a nice article about that: https://help.github.com/articles/about-pull-requests/

**Comment by dilyanpalauzov** [comment]
Why does cyrus-sasl/configure print at the end CXXFLAGS?  The only references to .cxx is in the NTMakefile's.

Except  #339 is fixed, for the output of ./configure I suggest including the warning from `/Makefile.am:install-exec-local`. I guess people are more likely to read such overviews from ./configure, when provided, rather than digging the output of "make install".

**Comment by dilyanpalauzov** [comment]
```
Installation Directories
   Prefix ................: /usr/local
   Config dir ............: /usr/lib/sasl2:/etc/sasl2
   Plugin dir ............: /usr/lib/sasl2
   PRNG ..................: /dev/urandom
```

I mean adding here more detailed description, when ./configure is run:
```
  Directory where plugins will be installed: ........ ${prefix}/lib/sasl2 == /usr/local/lib/sasl2 (according to sasldir in plugins/Makefile.am)
  Directory where plugins will be searched for: ..... ${plugindir} == /usr/lib/sasl2
 ```

**Comment by dilyanpalauzov** [comment]
It prints $enable_shared right after "Static libraries".
