### ISSUE TITLE
saslpasswd2 not creating records for other mechanisms

### ISSUE THREAD

**Issue by UnitedMarsupials-zz** [cyrusimap/cyrus-sasl#481]
As I reported on the mailing list and [here](https://serverfault.com/questions/877434/), `saslpasswd2` would not create records other than `userPassword`.

Having added more details to its log-records as described in #480, I can see, that it
* is attempting to _delete_ the previous records for all of the mechanisms
* is failing in the above attempts, because the records aren't there:
```
Oct  8 17:38:34 symbion saslpasswd2: Couldn't delete record for test example.com cmusaslsecretCRAM-MD5 in db /opt/etc/sasldb2: No such file or directory
Oct  8 17:38:34 symbion saslpasswd2: Couldn't delete record for test example.com cmusaslsecretDIGEST-MD5 in db /opt/etc/sasldb2: No such file or directory
Oct  8 17:38:34 symbion saslpasswd2: Couldn't delete record for test example.com cmusaslsecretPLAIN in db /opt/etc/sasldb2: No such file or directory
Oct  8 17:38:34 symbion saslpasswd2: DIGEST-MD5 common mech free
```
* then creates only the `userPassword` record:
```
test@example.com: userPassword
```
If I am doing something wrong, there is got to be an error- or warning- message to the effect... And not just in the log-file...

**Comment by UnitedMarsupials** [comment]
Although originally observed on FreeBSD with 2.1.26, I can reproduce this exact same problem on Ubuntu (`trusty`) -- using version 2.1.25.

**Comment by UnitedMarsupials** [comment]
Unfortunately, using 2.1.27 (rc5) does not help either...

**Comment by UnitedMarsupials** [comment]
Looking in `lib/server.c`, I see, that the code will not even attempt to create a mechanism-specific record, if the mechanism does not define `setpass` -- and `crammd5_server_plugins` does not...

What's happening?

**Comment by hyc** [comment]
All of those mechs only use userPassword now. The cmusaslsecret* fields were obsoleted long ago.
e.g., cram secret obsoleted in 2011 7506f11a2
