### ISSUE TITLE
sasl_server_start manpage shows wrong type for clientinlen argument

### ISSUE THREAD

**Issue by neirbowj** [cyrusimap/cyrus-sasl#491]
[`sasl_server_start(3)`](https://github.com/cyrusimap/cyrus-sasl/blob/39935b8f416f749ab5ef0c9c17b388690f47ee00/man/legacy/sasl_server_start.3#L53) contains

```
.BI "int sasl_server_start(sasl_conn_t * " conn ", "
.BI "		           const char * " mech ", "
.BI "		           const char * " clientin ", "
.BI "		           unsigned * " clientinlen ", "
.BI "		           const char ** " serverout ", "
.BI "		           unsigned * " serveroutlen ");"
```

Whereas [`sasl.h`](https://github.com/cyrusimap/cyrus-sasl/blob/39935b8f416f749ab5ef0c9c17b388690f47ee00/include/sasl.h#L1091) declares the the function as

```
LIBSASL_API int sasl_server_start(sasl_conn_t *conn,
				  const char *mech,
				  const char *clientin,
				  unsigned clientinlen,
				  const char **serverout,
				  unsigned *serveroutlen);
```

**Comment by ksmurchison** [comment]
Fixed by https://github.com/cyrusimap/cyrus-sasl/commit/636ee94c4f9f7305fc6746305abeed3de8585763
