### ISSUE TITLE
Make code dependent of used openssl version

### ISSUE THREAD

**Issue by kohldampfer** [cyrusimap/cyrus-sasl#500]
Currently, when I am compiling the source code of cyrus-sasl on a Windows system against an OpenSSL version of 1.0.2, there are compiling / linking errors like this one:

> ntlm.c(481): warning C4013: 'HMAC_CTX_reset' undefined; assuming extern returning int
> ...
> ntlm.obj : error LNK2019: unresolved external symbol _HMAC_CTX_reset referenced in function _V2

Is it possible, to change the code in a way, so there is something like this
```
#if OPENSSL_VERSION_NUMBER == 0x100020cfL
    // Do stuff which can be done for OpenSSL 1.0.2
#elif OPENSSL_VERSION_NUMBER == 0x1....
    // Do stuff which can be done for OpenSSL 1.1.0
#endif
```

**Comment by Jakuje** [comment]
I don't see these problems on Linux, when building against `openssl-1.0.2k` -- there is already `common/crypto-compat.c`, which defines missing functions for 1.0.2 version.

**Comment by sfhacker** [comment]
We haven't had any issues building the latest SASL code using recent OpenSSL versions (including 1.0.2) on Windows. We even tried OpenSSL 1.1.1 (TLS 1.3) and it worked fine.

When we type pluginviewer, we see:

Installed and properly configured auxprop mechanisms are:
sasldb
List of auxprop plugins follows
Plugin "sasldb" ,       API version: 8
        supports store: yes

Installed and properly configured SASL (server side) mechanisms are:
  SCRAM-SHA-1 GSSAPI GSS-SPNEGO DIGEST-MD5 EXTERNAL OTP CRAM-MD5 NTLM LOGIN PLAIN ANONYMOUS
Available SASL (server side) mechanisms matching your criteria are:
  SCRAM-SHA-1 GSSAPI GSS-SPNEGO DIGEST-MD5 OTP CRAM-MD5 NTLM LOGIN PLAIN ANONYMOUS
List of server plugins follows
....
....
....

**Comment by hyc** [comment]
The referenced OpenSSL versions are obsolete.
