### ISSUE TITLE
installing for apple creates .so file and expects .plugin file

### ISSUE THREAD

**Issue by mehdadi** [cyrusimap/cyrus-sasl#508]
in file dlopen.c there is the definition to look for .plugin files in case ifdef(__Apple__) while all the files in the directory regarding to plugins are .so. I am wondering why? does it any mismatch somewhere or is I am miss to build .plugin files?

**Comment by nacho** [comment]
I just tried on osx and I can confirm this issue. I will prepare a pull request

**Comment by nacho** [comment]
Created pull request: https://github.com/cyrusimap/cyrus-sasl/pull/536

**Comment by mehdadi** [comment]
Thanks .

**Comment by ksmurchison** [comment]
PR merged
