### ISSUE TITLE
oauth2, postfix, smtp.openoffice365.com combination does not work

### ISSUE THREAD

**Issue by Claghorn** [cyrusimap/cyrus-sasl#511]
My postfix config that used office365 as a relayhost stopped working on fedora 28, which comes with lots of new versions of software, including cyrus-sasl. I submitted this fedora bug: [https://bugzilla.redhat.com/show_bug.cgi?id=1575424](url) with all the details, but the key observation I made was that mail started working when I restricted postfix to only use "login" for auth, not "xoauth2". This leads me to believe either microsoft or cyrus-sasl is to blame (I'd tend to guess microsoft).

**Comment by hyc** [comment]
xoauth2 is a 3rd party plugin, from https://github.com/moriyoshi/cyrus-sasl-xoauth2 and isn't part of the Cyrus SASL package. Sounds like you need to install that yourself separately.
