### ISSUE TITLE
Get rid of MD5 implementation and use OpenSSL

### ISSUE THREAD

**Issue by Jakuje** [cyrusimap/cyrus-sasl#513]
The issue #272 talked about multilib issue that we hit from time to time here in Fedora, between i686 and 86_64 architecture packages providing different versions of `md5global.h` header file.

In Fedora, we are solving the problem by removing the built-time creation of the architecture-specific file and use the one pregenerated in the tarball. This works fine for our architectures, but might not work for more obscure ones so I don't ask you to merge our patch:

https://src.fedoraproject.org/rpms/cyrus-sasl/blob/master/f/cyrus-sasl-2.1.26-md5global.patch

Is the MD5 implementation worth all the trouble? Can the cyrus-sasl use the OpenSSL implementation, since the dependency is already there in other places?

**Comment by nacho** [comment]
IMHO it would make sense using openssl directly

**Comment by simo5** [comment]
I took a look at this, and replacing the internal implementation with openssl md5 is not hard, however this will break one cram plugin feature, the ability to use a precomputed md5 secret called *cmusaslsecretCRAM-MD5
This is guarded by #if defined(OBSOLETE_CRAM_ATTR) however this is always defined to 1 as far as I can tell, so currently available to users.
No idea how much this is used and if it is worth preserving it, but at the very least using MD5 from openssl needs to be conditional to that define if this feature needs to be preserved

**Comment by bgermann** [comment]
#712 is actually a good argument to implement this.

**Comment by bgermann** [comment]
The precomputed MD5 secret only requires the HMAC part of the internal implementation as OpenSSL's HMAC interface does not expose the state. I have replaced all MD5 primitives in #767, keeping the HMAC part.

A nice side effect it that removing the code gets rid of most files that are licensed under RSA-MD. The only remaining file is lib/md5.c.
