### ISSUE TITLE
Source tarball releases do not contain m4 files or autogen.sh

### ISSUE THREAD

**Issue by mingwandroid** [cyrusimap/cyrus-sasl#515]
I need to run autoreconf or autogen.sh to build for a machine that the pre-baked configure script cannot detect correctly (and for other reasons).

There is no `autogen.sh` provided with the latest release and `autoreconf -vfi` does not work. I have installed libtool, autoconf and automake.

My best attempt so far:
```
ACLOCAL_FLAGS=${BUILD_PREFIX}/share/aclocal aclocal --install -I.
autoreconf --verbose --force --install -Wno-portability -I.
```

Results in:
```
aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'
aclocal: installing './libtool.m4' from '/root/worker/containers/000021ceo0o/tmp/build/80754af9/cyrus-sasl_1527076210717/_build_env/share/aclocal/libtool.m4'
aclocal: installing './ltoptions.m4' from '/root/worker/containers/000021ceo0o/tmp/build/80754af9/cyrus-sasl_1527076210717/_build_env/share/aclocal/ltoptions.m4'
aclocal: installing './ltsugar.m4' from '/root/worker/containers/000021ceo0o/tmp/build/80754af9/cyrus-sasl_1527076210717/_build_env/share/aclocal/ltsugar.m4'
aclocal: installing './ltversion.m4' from '/root/worker/containers/000021ceo0o/tmp/build/80754af9/cyrus-sasl_1527076210717/_build_env/share/aclocal/ltversion.m4'
aclocal: installing './lt~obsolete.m4' from '/root/worker/containers/000021ceo0o/tmp/build/80754af9/cyrus-sasl_1527076210717/_build_env/share/aclocal/lt~obsolete.m4'
autoreconf: Entering directory `.'
autoreconf: configure.in: not using Gettext
autoreconf: running: aclocal -I . --force --warnings=no-portability 
aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'
autoreconf: configure.in: tracing
autoreconf: configure.in: adding subdirectory saslauthd to autoreconf
autoreconf: Entering directory `saslauthd'
aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'
configure.in:166: warning: AC_CACHE_VAL(have_func, ...): suspicious cache-id, must contain _cv_ to be cached
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
configure.in:166: the top level
configure.in:175: warning: AC_CACHE_VAL(have_pretty_function, ...): suspicious cache-id, must contain _cv_ to be cached
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
configure.in:175: the top level
configure.in:184: warning: AC_CACHE_VAL(have_function, ...): suspicious cache-id, must contain _cv_ to be cached
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
configure.in:184: the top level
configure.in:166: warning: AC_CACHE_VAL(have_func, ...): suspicious cache-id, must contain _cv_ to be cached
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
configure.in:166: the top level
configure.in:175: warning: AC_CACHE_VAL(have_pretty_function, ...): suspicious cache-id, must contain _cv_ to be cached
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
configure.in:175: the top level
configure.in:184: warning: AC_CACHE_VAL(have_function, ...): suspicious cache-id, must contain _cv_ to be cached
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
configure.in:184: the top level
autoreconf: configure.in: not using Libtool
autoreconf: running: /root/worker/containers/000021ceo0o/tmp/build/80754af9/cyrus-sasl_1527076210717/_build_env/bin/autoconf --include=. --force --warnings=no-portability
configure.in:166: warning: AC_CACHE_VAL(have_func, ...): suspicious cache-id, must contain _cv_ to be cached
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
configure.in:166: the top level
configure.in:175: warning: AC_CACHE_VAL(have_pretty_function, ...): suspicious cache-id, must contain _cv_ to be cached
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
configure.in:175: the top level
configure.in:184: warning: AC_CACHE_VAL(have_function, ...): suspicious cache-id, must contain _cv_ to be cached
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
configure.in:184: the top level
configure.in:14: error: possibly undefined macro: AC_DEFINE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /root/worker/containers/000021ceo0o/tmp/build/80754af9/cyrus-sasl_1527076210717/_build_env/bin/autoconf failed with exit status: 1
```

**Comment by sfhacker** [comment]
It is working here!

$ ./autogen.sh
libtoolize: found 'configure.ac'
libtoolize: export M4='/bin/m4.exe'
libtoolize: ac_aux_dir='config'
libtoolize: ltdl mode=''
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: cp -f /mingw/share/libtool/build-aux/config.guess config
libtoolize: cp -f /mingw/share/libtool/build-aux/config.sub config
libtoolize: cp -f /mingw/share/libtool/build-aux/install-sh config
libtoolize: cp -f /mingw/share/libtool/build-aux/ltmain.sh config
libtoolize: found 'Makefile.am'
libtoolize: aclocal_amflags=-I m4'
libtoolize: am_macro_dir='m4'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: cp -f /mingw/share/aclocal/libtool.m4 m4
libtoolize: Not copying 'm4/ltargz.m4', libltdl not used.
libtoolize: Not copying 'm4/ltdl.m4', libltdl not used.
libtoolize: cp -f /mingw/share/aclocal/ltoptions.m4 m4
libtoolize: cp -f /mingw/share/aclocal/ltsugar.m4 m4
libtoolize: cp -f /mingw/share/aclocal/ltversion.m4 m4
libtoolize: cp -f /mingw/share/aclocal/lt~obsolete.m4 m4
libtoolize: found LT_INIT invocation
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: copying file 'config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /mingw/bin/autoconf --force
autoreconf: running: /mingw/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:97: installing 'config/compile'
configure.ac:70: installing 'config/missing'
common/Makefile.am: installing 'config/depcomp'
autoreconf: Leaving directory `.'

**Comment by mingwandroid** [comment]
I am referring to the most recently released tarball not the GitHub sources.

**Comment by sfhacker** [comment]
I just unzipped  'cyrus-sasl-2.1.27-rc8.tar.gz', copied autogen.sh from GitHub and worked like a charm.
There is a folder called 'm4' with 18 files. 
Can you email me your tarball so I can tested locally?

noah@DESKTOP-QDSFRSF /src/cyrus-sasl-2.1.27
$ ./autogen.sh
libtoolize: found 'configure.ac'
libtoolize: export M4='/bin/m4.exe'
libtoolize: ac_aux_dir='config'
libtoolize: ltdl mode=''
libtoolize: rm -f 'config/compile'
libtoolize: rm -f 'config/depcomp'
libtoolize: rm -f 'config/missing'
libtoolize: rm -f 'config/ltmain.sh'
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: cp -f /mingw/share/libtool/build-aux/config.guess config
libtoolize: cp -f /mingw/share/libtool/build-aux/config.sub config
libtoolize: cp -f /mingw/share/libtool/build-aux/install-sh config
libtoolize: cp -f /mingw/share/libtool/build-aux/ltmain.sh config
libtoolize: found 'Makefile.am'
libtoolize: aclocal_amflags=-I m4'
libtoolize: am_macro_dir='m4'
libtoolize: rm -f 'm4/libtool.m4'
libtoolize: rm -f 'm4/ltoptions.m4'
libtoolize: rm -f 'm4/ltsugar.m4'
libtoolize: rm -f 'm4/ltversion.m4'
libtoolize: rm -f 'm4/lt~obsolete.m4'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: cp -f /mingw/share/aclocal/libtool.m4 m4
libtoolize: Not copying 'm4/ltargz.m4', libltdl not used.
libtoolize: Not copying 'm4/ltdl.m4', libltdl not used.
libtoolize: cp -f /mingw/share/aclocal/ltoptions.m4 m4
libtoolize: cp -f /mingw/share/aclocal/ltsugar.m4 m4
libtoolize: cp -f /mingw/share/aclocal/ltversion.m4 m4
libtoolize: cp -f /mingw/share/aclocal/lt~obsolete.m4 m4
libtoolize: found LT_INIT invocation
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: copying file 'config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /mingw/bin/autoconf --force
autoreconf: running: /mingw/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:97: installing 'config/compile'
configure.ac:70: installing 'config/missing'
common/Makefile.am: installing 'config/depcomp'
autoreconf: Leaving directory `.'
