### ISSUE TITLE
saslauthd(8) is rendered ahead of time

### ISSUE THREAD

**Issue by ddevault** [cyrusimap/cyrus-sasl#519]
It looks like the mdoc is converted to raw ANSI terminal instructions via nroff before it's installed:

https://github.com/cyrusimap/cyrus-sasl/blob/e41cfb986c1b1935770de554872247453fdbb079/saslauthd/Makefile.am#L43

This doesn't really make sense, and it breaks the man viewer's ability to render it correctly. We can just install the roff file instead.

**Comment by Jakuje** [comment]
Related #504

**Comment by quanah** [comment]
related to #373 as well.
