### ISSUE TITLE
subscribe to maillist - not working

### ISSUE THREAD

**Issue by aixtools** [cyrusimap/cyrus-sasl#520]
Page https://github.com/cyrusimap/cyrus-sasl says:
There's a mailing list for Cyrus SASL. Subscribe by sending a message to majordomo@lists.andrew.cmu.edu with the body "subscribe cyrus-sasl".

However, mail is immediately returned with:
  ----- The following addresses had permanent fatal errors -----
<majordomo@lists.andrew.cmu.edu>
    (reason: 553 5.3.0 <majordomo@lists.andrew.cmu.edu>... Unknown list majordomo.  See <http://lists.andrew.cmu.edu/>)

FYI

**Comment by dilyanpalauzov** [comment]
You can subscribe at https://lists.andrew.cmu.edu/mailman/listinfo/cyrus-sasl  .

It seems like CMU changed from majordomo to mailman, maybe in November 2017, so somebody is supposed to update both the subscription procedure and the archive link to https://lists.andrew.cmu.edu/pipermail/cyrus-sasl/.

**Comment by aixtools** [comment]
FYI: I got subscribed long ago. so closing issue. Thx.
