### ISSUE TITLE
New Release / Broken Build

### ISSUE THREAD

**Issue by sfhacker** [cyrusimap/cyrus-sasl#538]
Thanks for taking care of this new release. @ksmurchison 

Unfortunately, some of the changes have broken the build.

a) Unable to find 'VersionHelpers.h' file anywhere within this repository
     It seems to be part of Windows Driver Kit (UM)?
   
libtool  --tag=CC   --mode=compile gcc.exe -DHAVE_CONFIG_H -I. -I../../common -I..  -fPIC -I../../include -I../include -DOBSOLETE_CRAM_ATTR=1 -DOBSOLETE_DIGEST_ATTR=1  -Wall -W -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 -D_WIN32_IE=0x0501 -DPTW32_STATIC_LIB -D__CLEANUP_C -m64 -O2 -pipe -mms-bitfields -fno-builtin -march=core2 -mtune=core2 -MT plugin_common.lo -MD -MP -MF $depbase.Tpo -c -o plugin_common.lo ../../common/plugin_common.c &&\
        mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc.exe -DHAVE_CONFIG_H -I. -I../../common -I.. -fPIC -I../../include -I../include -DOBSOLETE_CRAM_ATTR=1 -DOBSOLETE_DIGEST_ATTR=1 -Wall -W -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 -D_WIN32_IE=0x0501 -DPTW32_STATIC_LIB -D__CLEANUP_C -m64 -O2 -pipe -mms-bitfields -fno-builtin -march=core2 -mtune=core2 -MT plugin_common.lo -MD -MP -MF .deps/plugin_common.Tpo -c ../../common/plugin_common.c -o plugin_common.o
../../common/plugin_common.c:49:29: fatal error: VersionHelpers.h: No such file or directory
 #include <VersionHelpers.h>
                             ^
compilation terminated.
make[2]: *** [plugin_common.lo] Error 1
make[2]: Leaving directory `/src/cyrus-sasl-cyrus-sasl-2.1.27/build/common'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/src/cyrus-sasl-cyrus-sasl-2.1.27/build'
make: *** [all] Error 2

b) What is the point of all these #defines _WIN32_WINNT_WINXP, _WIN32_WINNT_WIN7, etc, etc?

    They are all present in sdkddkver.h file
	
d) Have we included the fixes for the following pending issues in this new release?

        #523
       #516

**Comment by Ri0n** [comment]
I just checked mingw-w64 package. The header is there but it's all lower-case.

`./mingw-w64-headers/include/versionhelpers.h`

Could you please update the incude and retry?

**Comment by ksmurchison** [comment]
Can this include be #ifdef/#elsif/#endif protected with definitions detected at configure time?

**Comment by Ri0n** [comment]
I believe we can just always use the lower-case variant of the header.

**Comment by Ri0n** [comment]
any other build issue after replacing header name?

**Comment by Ri0n** [comment]
forgot to mention it here. I made a PR https://github.com/cyrusimap/cyrus-sasl/pull/541

**Comment by sfhacker** [comment]
Although a new Windows native release has been made available recently, we encourage people to contribute patches #539 .

Cheers.

**Comment by quanah** [comment]
Believe fixed in 2.1.28
