### ISSUE TITLE
Windows Native Build // Patches Call

### ISSUE THREAD

**Issue by sfhacker** [cyrusimap/cyrus-sasl#539]
**OS**         : Windows
**ARCH**    : x86_64

**SASL Version**: 2.1.27

**SASL DB**: MDB / Static & Dynamic

**PLUGINS**: SRP PASSDSS-3DES-1 SCRAM-SHA-256 SCRAM-SHA-1 GSS-SPNEGO GSSAPI 
                DIGEST-MD5 EXTERNAL OTP CRAM-MD5 NTLM LOGIN PLAIN ANONYMOUS

![sasl-plugins](https://user-images.githubusercontent.com/25817529/46770093-6aaa4480-ccc4-11e8-8814-047e3ca189b2.png)

**TOOLS**
    pluginviewer, sasldblistusers2, saslpasswd2, dbconverter-2

100% compatible with Microsoft compilers (e.g. cl)

![sasl-microsoft-compilers](https://user-images.githubusercontent.com/25817529/46770126-8f9eb780-ccc4-11e8-9873-a4754966f2ce.png)
	

**Dependencies**

    - OpenSSL 1.1.1
	- Kerberos: Heimdal 7.5.0
	
**Integration with other projects**
    
	- OpenLDAP 2.4.46

![openldap-sasl](https://user-images.githubusercontent.com/25817529/46770174-b78e1b00-ccc4-11e8-9933-49f0ee87fcea.png)

	
If you would like to see your patches merged into this coming release, 
do please contribute them as soon as possible.

Regards.

**Comment by Neustradamus** [comment]
Any news about it?

**Comment by sfhacker** [comment]
@Neustradamus I beg your pardon? This thread is one year old!

**Comment by Neustradamus** [comment]
@sfhacker: Have you done modifications?
Have you done a PR?

**Comment by sfhacker** [comment]
@Neustradamus The idea was that people could contribute their patches so I could make available a new release with all those patches included. There is no PR. A Windows native release was made availabe in Nov/2018.
Do you have something to contribute? I am preparing a new release for Christmas 2019.

**Comment by bgermann** [comment]
I guess this should be closed then.
