### ISSUE TITLE
Fallback on failure

### ISSUE THREAD

**Issue by timokau** [cyrusimap/cyrus-sasl#543]
I'm not quite sure where the responsibility actually lies here. After switching operating systems my emails wouldn't sync anymore (using isync with cyrus-sasl). The error it gave was

```
Error: SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (No Kerberos credentials available (default cache: FILE:/tmp/krb5cc_1000))
```

Turns out that is because my old distro had a separate `cyrus-sasl-gssapi` package which wasn't installed while my new distro ships gssapi-support by default. So my old distro was actually using `PLAIN` instead of `GSSAPI`.

Would it be possible to fall back to different mechanism if one mechanism fails (`PLAIN` instead of `GSSAPI` here)?

Feedback on possible actual causes for the GSSAPI error would also be appreciated.

**Comment by jboynyc** [comment]
I have the same problem @timokau described, and his proposed fix sounds like it would mitigate the issue.

**Comment by timokau** [comment]
I can no longer reproduce this issue.
