### ISSUE TITLE
SCRAM Mechanism returns incorrect error code on wrong password

### ISSUE THREAD

**Issue by quanah** [cyrusimap/cyrus-sasl#545]
This was incorrectly reported to the OpenLDAP project: https://www.openldap.org/its/index.cgi/?findid=8936

The code remains wrong in current cyrus-sasl master:

```
1431     for (k = 0; k < hash_size; k++) {
1432     if (CalculatedStoredKey[k] != text->StoredKey[k]) {
1433         SETERROR(sparams->utils, "StoredKey mismatch");
1434         result = SASL_BADPROT;
1435         goto cleanup;
1436     }
```

**Comment by Neustradamus** [comment]
@quanah: Any news?

**Comment by quanah** [comment]
@Neustradamus This project appears to primarily be ignored by Fastmail, so no.

**Comment by Neustradamus** [comment]
@ksmurchison: What do you think about this ticket from @quanah?

SCRAM is very important for projects which use it, currently it is very limited.

@brong, @ksmurchison, do not forget: There is a problem of priority for SCRAM-SHA-256 and SCRAM-SHA-1:
- https://github.com/cyrusimap/cyrus-sasl/pull/577

Any news for other points?
- https://github.com/cyrusimap/cyrus-sasl/issues/552

It is easy to add -PLUS part, no?

Documentation problems:
- https://github.com/cyrusimap/cyrus-sasl/issues/549

**Comment by ksmurchison** [comment]
Is there a PR to fix the error code?

**Comment by quanah** [comment]
> Is there a PR to fix the error code?

There is now. :)

**Comment by Neustradamus** [comment]
@ksmurchison, @quanah: Thanks for your changes but any news for tickets cited previously?
- #577
- #552
- #549
