### ISSUE TITLE
default saslauth account

### ISSUE THREAD

**Issue by ttandqq** [cyrusimap/cyrus-sasl#570]
When I do "yum install cyrus-sasl-devel" on linux,why always create default "saslauth" account in /etc/passwd? Can I delete it if I do not use saslauthd service?Is there any way that do not create this account default?

**Comment by quanah** [comment]
That would be a question for your linux distribution provider.  The source code does not do this.

**Comment by ttandqq** [comment]
@quanah ok,thanks
