### ISSUE TITLE
ntlm plugin: ntlm_v2 option is not read from the configuration file by client

### ISSUE THREAD

**Issue by yarda** [cyrusimap/cyrus-sasl#574]
It's problem with e.g. postfix where you cannot set ntlm_v2 to be the default for the client.

Reproducer:
* setup cyrus-sasl to use NTLMv2 for the postfix client
* add 'ntlm_v2: yes" to the /etc/sasl2/smtp.conf (postfix client uses smtp service)

the configuration file /etc/sasl2/smtp.conf is not read by the sasl library. By quick inspection of the code it seems the config loader is not implemented for the client, so there is no way how to specify the ntlm_v2 configuration parameter in the postfix.

Downstream bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=1722159

**Comment by quanah** [comment]
Per the BZ conversation, definitely a bug, but the problem is rather deep as cyrus-sasl currently lacks the ability to set this on the client side.

**Comment by simo5** [comment]
@quanah I have this on my radar due to customer request.
What solution would be acceptable to cyrus-sasl in order to provide client options ?

**Comment by bgermann** [comment]
This will be solved on implementation of #708

**Comment by quanah** [comment]
Superseded by #708
