### ISSUE TITLE
Cannot compile with specific OpenSSL version (openssl/evp.h not found)

### ISSUE THREAD

**Issue by xperseguers** [cyrusimap/cyrus-sasl#581]
Hi there,

I'm trying to build the LDAP PHP extension with SSL support and it requires SASL, so I want to compile Cyrus-SASL and since I know OpenSSL is ticky, I built the exact same version of OpenSSL as used by my PHP version, which is 1.0.2o.

I have ```BUILD_DIR=/tmp/build```

Then I compile OpenSSL:

```
cd /tmp
wget https://github.com/openssl/openssl/archive/OpenSSL_1_0_2o.tar.gz
tar xzf OpenSSL_1_0_2o.tar.gz
cd openSSL-OpenSSL_1_0_2o
./Configure darwin64-x86_64-cc shared --openssldir=${BUILD_DIR} && make clean && make && make install
```

In `${BUILD_DIR}/include` I find `openssl/evh.h`.

Now trying to compile Cyrus-SASL:

```
git clone https://github.com/cyrusimap/cyrus-sasl.git
./autogen.sh --prefix=${BUILD_DIR} --with-openssl=${BUILD_DIR}
```

gives errors:

```
checking what directory libraries are found in... (cached) lib
checking for RSAPublicEncrypt in -lrsaref... (cached) no
checking for openssl/evp.h... (cached) no
checking for OpenSSL... no
checking for des_cbc_encrypt in -ldes... (cached) no
checking for des_cbc_encrypt in -ldes425... (cached) no
checking for des_cbc_encrypt in -ldes524... (cached) no
checking for RSAPublicEncrypt in -lrsaref... (cached) no
checking for des_cbc_encrypt in -lcrypto... (cached) no
```

I tried various things, compiling OpenSSL with the `shared` parameter, linking `build/lib64` to `build/lib`, adding environment variables before calling `./autogen.sh`:

```
export LDFLAGS="-L${BUILD_DIR}/lib -R${BUILD_DIR}/lib"
export CFLAGS="-I${BUILD_DIR}/include:${BUILD_DIR}/openssl"
./autogen.sh --prefix=${BUILD_DIR} --with-openssl=${BUILD_DIR}
```

no matter what, it never finds `openssh/evp.h`!

Could someone help please? Thanks!

**Comment by manang** [comment]
did you find a solution?
thanks

**Comment by hyc** [comment]
Looks like you had a stale config.cache.

OpenSSL 1.0.2 is long since obsolete. Closing this.
