### ISSUE TITLE
Determination of own FQDN fails on GSSAPI server when FQDN is 64 characters or longer

### ISSUE THREAD

**Issue by toddlipcon** [cyrusimap/cyrus-sasl#583]
Currently the `get_fqhostname` function assumes that the FQDN can be no longer than `MAXHOSTNAMELEN`. This is an incorrect assumption -- that constant (typically 64) only applies to the max _unqualified_ hostname. In fact, it's legal to have a FQDN which is 253 bytes long.

This results in truncation of the determined hostname.

In addition, the truncation is performed using `strncpy()` from the result if the DNS lookup into the result buffer, which does _not_ null terminate the result in the case that the result buffer doesn't have enough space. Then in `_sasl_conn_init` this non-null-terminated buffer is used as an argument to `strdup` meaning it ends up appending some garbage bytes from the stack following the buffer (until it happens to hit a null byte). The resulting error message then looks something like `No key table entry found matching impala/multidistro-191030-070716-e7r-dw3-coordinator0.multidis.xcu2-8y8xwˆyÿ@)` (note the junk at the end).

As a workaround, users can pass in an explicit FQDN.

**Comment by quanah** [comment]
Valid issue, MAXHOSTNAMELEN is only for the unqualified hostname as noted.

**Comment by simo5** [comment]
@toddlipcon looking at this I see:
#define MAXHOSTNAMELEN 255 in config.h is MAXHOSTNAMELEN is not defined ...

i guess the problme is that on OSs like Linux param.h defined MAXHOSTNAMELEN 64 ?

**Comment by quanah** [comment]
@simo5 no, the problem is that MAXHOSTNAMELEN was never meant to be for FQDN and shouldn't be used as such.

**Comment by simo5** [comment]
@quanah I have a patch almost ready :-)
