### ISSUE TITLE
Feature idea: Make CyrusSASL store Kerberos tokens for delegation

### ISSUE THREAD

**Issue by aiobofh** [cyrusimap/cyrus-sasl#585]
If one write a service with SASL and GSSAPI authentication, it would be awesome to have a way to forward/delegate that user authentication to other underlying services and subsystems.

I have a working (GSSProxy compatible) concept for this that allows for any service using CyrusSASL to make this a reality. A minor improvement to plugins/gssapi.c that make use of a few new key/value pairs for that service in the sasl2-configuration file for that service. E.g. where to store ccreds and a naming schema along with information on persistence for autonomous impersonation. 

Waiting for @aamelnikov on how to best contribute.

**Comment by aiobofh** [comment]
@aamelnikov is the pull-request a good way to get the code in?

**Comment by quanah** [comment]
merged
