### ISSUE TITLE
SHA-256 + SHA-512/256

### ISSUE THREAD

**Issue by Neustradamus** [cyrusimap/cyrus-sasl#590]
Why I request new parameters?
It is for new SIP which replace old...

RFC8760: The Session Initiation Protocol (SIP) Digest Access Authentication Scheme: https://tools.ietf.org/html/rfc8760
- SHA-256
- SHA-512/256

**Comment by quanah** [comment]
DIGEST-MD5 has been deleted so no longer applicable.
