### ISSUE TITLE
Issues with msvc 2019 (32bits)

### ISSUE THREAD

**Issue by raniervf** [cyrusimap/cyrus-sasl#606]
With msvc 2019 (32bits) have this issues:

1. cyrus-sasl\plugins\ntlm.c(827)
SOCKET is unsigned value, so it can't be -1, can be only INVALID_SOCKET.
Please review this in case fail, must be return INVALID_SOCKET with win32.

2. cyrus-sasl\plugins\ntlm.c(2127)
free_password uninitialized var used.
fix: (line 1988)
    unsigned int free_password = 0; /* set if we need to free password */

3. cyrus-sasl\plugins\scram.c(1388)
proof_offset uninitialized var used.

4. cyrus-sasl\lib\common.c(102)
address of dllimport 'malloc' is not static identity not guaranteed
address of dllimport 'calloc' is not static identity not guaranteed
address of dllimport 'realloc' is not static identity not guaranteed
address of dllimport 'free' is not static identity not guaranteed

**Comment by hyc** [comment]
1, 2 ntlm plugin has been removed
3 false, proof_offset is initialized when client_proof is set
4 don't care, 32bit is end of life.
