### ISSUE TITLE
cannot find -lpq

### ISSUE THREAD

**Issue by iretich** [cyrusimap/cyrus-sasl#608]
%bcond_with     pgsql
....
and I tried different cases:
--with-pgsql
--with-pgsql=/usr/local
--with-pgsql=/usr/local/pgsql
--with-pgsql-libdir=/usr/local/pgsql/lib
but everytime got following:
....
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -I../lib -I../sasldb -I../common -I../include -DOBSOLETE_CRAM_ATTR=1 -DOBSOLETE_DIGEST_ATTR=1 -I/usr/local/pgsql/include -Wall -W -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -c pgsql_init.c  -fPIC -DPIC -o .libs/pgsql_init.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -I../lib -I../sasldb -I../common -I../include -DOBSOLETE_CRAM_ATTR=1 -DOBSOLETE_DIGEST_ATTR=1 -I/usr/local/pgsql/include -Wall -W -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -c pgsql_init.c -o pgsql_init.o >/dev/null 2>&1
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -Wall -W -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -lpq -module -export-dynamic -rpath /usr/lib64/sasl2 -version-info 3:0:0 -no-undefined -Wl,-z,relro  -o libpgsql.la  pgsql.lo pgsql_init.lo  ../common/libplugin_common.la 
libtool: link: gcc -shared  -fPIC -DPIC  .libs/pgsql.o .libs/pgsql_init.o  -Wl,--whole-archive ../common/.libs/libplugin_common.a -Wl,--no-whole-archive  -lpq  -O2 -g -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -Wl,-z -Wl,relro   -Wl,-soname -Wl,libpgsql.so.3 -o .libs/libpgsql.so.3.0.0
/bin/ld: cannot find -lpq
collect2: error: ld returned 1 exit status
make[2]: *** [libpgsql.la] Error 1
make[2]: Leaving directory `/root/rpmbuild/BUILD/cyrus-sasl-2.1.27/plugins'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/rpmbuild/BUILD/cyrus-sasl-2.1.27'
make: *** [all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.5ffJPb (%build)

Is it your error in cyrus-sasl-2.1.27 version scripts for CentOS 7 or something sasl configuration nuance? If it the second then write what is it please.

**Comment by quanah** [comment]
duplicate of #609
