### ISSUE TITLE
RPM build errors: Explicit %attr() mode not applicaple to symlink & File must begin with "/"

### ISSUE THREAD

**Issue by iretich** [cyrusimap/cyrus-sasl#609]
Also there is broken rpm build script:

RPM build errors:
    Explicit %attr() mode not applicaple to symlink: /root/rpmbuild/BUILDROOT/cyrus-sasl-2.1.27-1.x86_64/usr/lib64/libsasl2.so.3
    Explicit %attr() mode not applicaple to symlink: /root/rpmbuild/BUILDROOT/cyrus-sasl-2.1.27-1.x86_64/usr/lib64/libsasl2.so
    Explicit %attr() mode not applicaple to symlink: /root/rpmbuild/BUILDROOT/cyrus-sasl-2.1.27-1.x86_64/usr/lib64/libsasl.so
    File must begin with "/": %{_pkgconfigdir}/libsasl2.pc

**Comment by flowerysong** [comment]
The only RPM spec in this repository is https://github.com/cyrusimap/cyrus-sasl/blob/master/config/sasl.spec , which is incredibly old and also cannot result in the error you've shown. I suggest contacting whomever wrote the spec file you are using.

**Comment by iretich** [comment]
So you mean there is no adequate spec file for version 2.1.x??

**Comment by flowerysong** [comment]
No, I mean that RPM packages are not maintained by this project.

I believe there are several adequate spec files since it is widely packaged, but any problems you encounter with those spec files are outside of the scope of this project and should be addressed to the maintainers of the spec file.
