### ISSUE TITLE
RPM build errors: Explicit %attr() mode not applicaple to symlink & File not found by glob: libmysql.so

### ISSUE THREAD

**Issue by iretich** [cyrusimap/cyrus-sasl#610]
The next errors during building RPM:
RPM build errors:
    Explicit %attr() mode not applicaple to symlink: /root/rpmbuild/BUILDROOT/cyrus-sasl-2.1.27-1.x86_64/usr/lib64/sasl2/libanonymous.so
    Explicit %attr() mode not applicaple to symlink: /root/rpmbuild/BUILDROOT/cyrus-sasl-2.1.27-1.x86_64/usr/lib64/sasl2/libanonymous.so.3
    Explicit %attr() mode not applicaple to symlink: /root/rpmbuild/BUILDROOT/cyrus-sasl-2.1.27-1.x86_64/usr/lib64/sasl2/libcrammd5.so
    Explicit %attr() mode not applicaple to symlink: /root/rpmbuild/BUILDROOT/cyrus-sasl-2.1.27-1.x86_64/usr/lib64/sasl2/libcrammd5.so.3
    Explicit %attr() mode not applicaple to symlink: /root/rpmbuild/BUILDROOT/cyrus-sasl-2.1.27-1.x86_64/usr/lib64/sasl2/libdigestmd5.so
    Explicit %attr() mode not applicaple to symlink: /root/rpmbuild/BUILDROOT/cyrus-sasl-2.1.27-1.x86_64/usr/lib64/sasl2/libdigestmd5.so.3
    Explicit %attr() mode not applicaple to symlink: /root/rpmbuild/BUILDROOT/cyrus-sasl-2.1.27-1.x86_64/usr/lib64/sasl2/liblogin.so
    Explicit %attr() mode not applicaple to symlink: /root/rpmbuild/BUILDROOT/cyrus-sasl-2.1.27-1.x86_64/usr/lib64/sasl2/liblogin.so.3
    File not found by glob: /root/rpmbuild/BUILDROOT/cyrus-sasl-2.1.27-1.x86_64/usr/lib64/sasl2/libmysql.so*

Does anybody check the code for mistakes?
I disabled mysql but your scripts are trying to build it anyway!

**Comment by quanah** [comment]
duplicate of #609
