### ISSUE TITLE
Any plans to make new rlease?

### ISSUE THREAD

**Issue by kloczek** [cyrusimap/cyrus-sasl#612]
It is already ~1.5 year  since last rlease and one CVE fix commited to the tree. I think that it would be good to flush currently committed changes and make new release :)

**Comment by kloczek** [comment]
And if may I ask to consider change tagging convention because current one as git automatically adds to the base directory repositorry name is causeing that https://github.com/cyrusimap/cyrus-sasl/archive/cyrus-sasl-2.1.27.tar.gz has `cyrus-sasl-cyrus-sasl-2.1.27/`

Simple not always dist tar ball are usefull and sometimes is good to use tagget one.

Just pelase use only version string with dots and without `cyrus-sasl`.

Thx

**Comment by quanah** [comment]
duplicate #580
