### ISSUE TITLE
Suggestion for DIGEST-MD5 unwrap() error for python-sasl library

### ISSUE THREAD

**Issue by elukey** [cyrusimap/cyrus-sasl#614]
Hi everybody,

this issue is not related to a bug of cyrus-sasl, but it is more a request to help me understand what the cyrus-sasl library needs in my use case. If you have time to follow up I'd be really grateful :)

Context: I am using https://github.com/sparkur/python-sasl3, a Python wrapper of this library, to add RPC encryption to https://github.com/internetarchive/snakebite-py3, a Hadoop HDFS client written in Python that I co-maintain. Sadly I am not sure if the python-sasl3 library is maintained, it was forked from another library to get more up to date bindings but there might little support for it (as far as I know at least).

The snakebite HDFS client part that I am writing is about RPC encryption, and does something like the following:

- SASL connection handshake for DIGEST-MD5 (client -> HDFS Server, a datanode)
- The negotiated security support is auth-conf.
- Once the SASL handshake is completed, the HDFS server sends AES keys to encrypt the communication, but using the DIGEST-MD5's wrap() functionality (so encrypting via rc4/3des).
- Once the keys are decrypted on the client side, then both parties have all the necessary info to start a AES encrypted communication channel.

The problem that I have is that after the handshake (that from debug logging seems to be fine), once it is time to call unwrap() I get the following error on the client:

`Error in sasl_decode (-1) SASL(-1): generic failure: Unable to find a callback: 32775'`

I traced it back to https://github.com/cyrusimap/cyrus-sasl/blob/master/include/sasl.h#L669, but from the documentation and examples I don't get what is the purpose of the callback.

In https://github.com/sparkur/python-sasl3/blob/master/sasl/saslwrapper.h#L187-L197 I see that some callbacks are defined, but I am not sure how SASL_CB_CANON_USER should behave.

These are some details about what the client sees:

```
username="518392067 BP-1073844472-10.64.36.128-1585217240940 NM0OWTiZ540=",realm="0",nonce="xxxxxxxxxx",cnonce="xxxxxxxxxxxx",nc=00000001,qop=auth-conf,cipher=rc4,maxbuf=65535,digest-uri="hdfs/0",response=xxxxxxxxxxxx
```

How do I know that it works? From the client side I see the HDFS Server protocol buffer message correctly with the AES encrypted keys, but I cannot unwrap() their content.

I hope this story is not too confusing, I am not super expert in SASL. Thanks in advance for the help!

**Comment by elukey** [comment]
Added something like the following:

```
+int ClientImpl::cbCanonUser(sasl_conn_t *conn,
+                           void *context,
+                           const char *user, unsigned ulen,
+                           unsigned flags,
+                           const char *user_realm,
+                           char *out_user, unsigned out_umax,
+                           unsigned *out_ulen)
+{
+    if (ulen > out_umax) {
+        return false;
+    }
+    memcpy(out_user, user, ulen);
+    *out_ulen = ulen;
+    return SASL_OK;
+}

```

It helped, but not the error is a "generic failure" without any more info.

**Comment by quanah** [comment]
DIGEST-MD5 is historic and should not be used.
