### ISSUE TITLE
FR: add the ability to use the client's IP in an SQL query

### ISSUE THREAD

**Issue by elliefm** [cyrusimap/cyrus-sasl#615]
@asy972 writes in https://github.com/cyrusimap/cyrus-imapd/issues/3072:

> Hello.
> 
> It would be nice to be able to use the client's IP address in an SQL query in sasl_sql_select in imapd.conf. This would allow to restrict IP access individually per E-Mail.

I believe this would need to be implemented in the `sql_select` option within cyrus-sasl, and not within cyrus-imapd, so I'm moving it here.

**Comment by asy972** [comment]
And client's hostname may be usable also.

**Comment by bgermann** [comment]
https://bugs.debian.org/689227 has an old patch implementing this. I guess it has to be reworked and documented for inclusion.

**Comment by quanah** [comment]
@bAndie91 would you be willing to submit your patch here to the project

**Comment by bAndie91** [comment]
> @bAndie91 would you be willing to submit your patch here to the project

oh, did i do this kind of stuff? ok, i can try to submit.

**Comment by quanah** [comment]
Thank you very much!
