### ISSUE TITLE
slow response, client timeout

### ISSUE THREAD

**Issue by LaKing** [cyrusimap/cyrus-sasl#630]
We use saslauthd 2.1.27 with postfix and rimap authentication. We experience a strange issue after an update: terribly slow response times soon after a restart.

If the saslauthd process is restarted, the response is fast, under one second. Then a few seconds later response is around one second. After one minute several seconds, and after several minutes up to several minutes.

While testsaslauthd always gives a response after a certain time, the mailing client's timeout.

The imap servers respond normally, so it seems to be an issue with saslauthd. Anyone has any ideas how to troubleshoot this?

**Comment by LaKing** [comment]
Setting option "-n 0" seems to have resolved the issue.

**Comment by quanah** [comment]
closing, no actionable information.
