### ISSUE TITLE
Use of MD4_DIGEST_LENGTH

### ISSUE THREAD

**Issue by kraj** [cyrusimap/cyrus-sasl#632]
when md4 is disabled in openssl then ntlm support can not compile because its looking for `MD4_DIGEST_LENGTH` which is then not exported by openSSL

https://github.com/cyrusimap/cyrus-sasl/blob/master/plugins/ntlm.c#L481

I wonder if it should be using `MD5_DIGEST_LENGTH` here

**Comment by quanah** [comment]
Need to review if some mechanisms should be dropped entirely for 2.1.28
