### ISSUE TITLE
Update documentation on Channel Binding

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-sasl#636]
The table at https://www.cyrusimap.org/sasl/sasl/authentication_mechanisms.html#summary says that the only mechanism, supporting Channel Binding, is G2.  G2 shall be renamed to GS2.  GSSAPI and SCRAM also support channel binding.

The same page references the mechanisms SCRAM-SHA-...-PLUS, but not GS2-KRB5-PLUS and GSSAPI-PLUS.

For the HTTP Profile on SCRAM the page has `?`.  Considering that SCRAM authentication was added to Cyrus IMAP with https://github.com/cyrusimap/cyrus-imapd/commit/4b64b6f03ca2e2dfb in 2017, this should mean that there is HTTP profile for SCRAM.

`-PLUS` means Channel Binding.

**Comment by dilyanpalauzov** [comment]
... in particular provide examples how to use struct sasl_channel_binding: what to use in name, data and len.  If name is the protocol, then replace in sample/server.c cb.name with "sample-application-protocol” and cb.data with "tls-unique:this is a test”, or something like this.

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/cyrusimap/cyrus-sasl/issues/549

**Comment by quanah** [comment]
Because it requires someone to write up all that example documentation they are asking for, and that's not as urgent as getting the release out.

**Comment by Neustradamus** [comment]
@dilyanpalauzov, @quanah: Happy New Year 2022!
It is good for 2.1.28?

**Comment by dilyanpalauzov** [comment]
> It is good for 2.1.28?

You are kindly asked to propose a patch.

**Comment by Neustradamus** [comment]
A new RFC arrives, RFC 9266: Channel Bindings for TLS 1.3:
- https://www.rfc-editor.org/authors/rfc9266.html

**Comment by Neustradamus** [comment]
It is official for TLS 1.3 Binding!
- RFC 9266: Channel Bindings for TLS 1.3: https://tools.ietf.org/html/rfc9266

Details:
- tls-unique for TLS =< 1.2
- tls-exporter for TLS = 1.3

**Comment by quanah** [comment]
This ticket was about the documentation, which was done.  Will open a separate request in regard to a code example.
