### ISSUE TITLE
Revert the Channel Binding changes in gssapi.c

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-sasl#637]
The GSSAPI SASL mechanism defined in [RFC 4752 The Kerberos V5 ("GSSAPI") SASL Mechanism ](https://tools.ietf.org/html/rfc4752) says explicitly, that Channel Binding is not supported.

The only SMTP server that support CB is exim (with gsasl, thus for SCRAM and not for GSSAPI), the only IMAP server supporting CB is Cyrus IMAP, no SMTP/IMAP client supports CB, except imtest (part of cyrus imap).

OpenLDAP intends to be compatible with Windows.  Windows apparently does not support GS2-KRB5-PLUS, or GS2-KRB5, but GSSAPI.  Windows can enforce Channel Binding over GSSAPI over LDAP and this is not compatible with RFC 4752.

Cyrus IMAP utilizes unconditionally the Channel Bindings API of Cyrus SASL and therefore can offer both SCRAM-SHA-1 and SCRAM-SHA-1-PLUS.  With the unconditional initialization of Channel Bindings, Cyrus IMAP together with the last change in gssapi.c enforces CB for GSSAPI over IMAP4, POP3, ManageSieve, HTTP/SPNEGO.

I understand OpenLDAP strives to function as Windows AD substitution, and for this non-RFC 4752 compliant GSSAPI SASL method must be used.  OpenLDAP has to achieve this however without the channel bindings in plugins/gssapi.c.  Otherwise Cyrus IMAP cannot offer, provided that it utilizes the API correct, SCRAM-SHA-1, SCRAM-SHA-1-PLUS and GSSAPI at the same time correctly (e.g. for Thunderbird and Evolution which do GSSAPI without Channel Binding, but might one day offer SCRAM with Channel Binding, too).

**Comment by iboukris** [comment]
In PR #601 I suggested to use an alternative option (like SASL_GSSAPI_CHANNEL_BINDING) to avoid side effects, but at the end why does Cyrus IMAP specify bindings for GSSAPI? That is clearly the bug.

**Comment by dilyanpalauzov** [comment]
Cyrus IMAP specifies bindings for Cyrus SASL.  These bindings are used then by all libsas2’s plugins: GS2 and SCRAM.  Because the bindings are offered, the methods GS2-KRB5-PLUS and SCRAM-SHA-1-PLUS are exported.

There is no way to specify bindings only for GSSAPI and not for GS2; or only for GS2 but not for GSSAPI.

**Comment by iboukris** [comment]
I see, so perhaps we do need an alternative option after all, let's see what others think.

**Comment by simo5** [comment]
@dilyanpalauzov GSSAPI is different!
GSSAPI specifies channel bindings at the protocol level, and it is required for compatibility with, by far, the largest deployment that makes use of this mechanism that the GSSAPI mechanism (not GSSAPI-PLUS) supports Channel bindings.
The problem is in enforcing, without gracefulness, the bindings in Cyrus IMAP.
I am against this simple revert because it is a net regression of code that is already in production for use wth the LDAP protocol.
We need to find a way to deal with this issue in libsasl2 itself at this point, it needs to special-case GSSAPI and understand that GSSAPI-PLUS is not a thing, just like GSS-SPNEGO-PLUS is not a thing.

**Comment by dilyanpalauzov** [comment]
The “C-language binding for Kerberos 5 (GSSAPI)” does permit Channel bindings.

The description of the “GSSAPI SASL” mechanism, described in RFC 4752, says in the Introduction:
> Note that the described authentication sequence has known limitations, in particular, it lacks channel bindings and the number of round-trips required to complete authentication exchange is not minimal.  SASL WG is working on a separate document that should address these limitations.

In “Section 3.1 Client Side of Authentication Protocol Exchange” the specification says:
> The client calls GSS_Init_sec_context, passing in … input_context_handle of 0 (initially), mech_type of the Kerberos V5 GSS-API mechanism [KRB5GSS], chan_binding of NULL, …

In “Section 3.2 3.2.  Server Side of Authentication Protocol Exchange” the specification contains:
> The server passes the initial client response to GSS_Accept_sec_context as input_token, setting input_context_handle to 0 (initially), chan_binding of NULL,

In “Section 5.  Security Considerations” the specification says:
>  For compatibility with deployed software, this document requires that the chan_binding (channel bindings) parameter to GSS_Init_sec_context and GSS_Accept_sec_context be NULL, hence disallowing use of GSS-API support for channel bindings.  GSS-API channel bindings in SASL is expected to be supported via a new GSS-API family of SASL mechanisms (to be introduced in a future document).

That said, what the largest deployment that makes use of the SASL GSSAPI mechanism does, is a violation of RFC 4752.  They call SASL GSSAPI something, that is not SASL GSSAPI.  The largest deployment can afford doing this, because… they are the largest deployments and historically have demonstrated not to follow standards in order to get commercial benefit of this policy.

Since Cyrus IMAP offers the mechanisms SASL GS2-KRB5, GS2-KRB5-PLUS and GSSAPI, by utilizing libsasl2 correctly, I do not see how does Cyrus IMAP enforce channel binding.

**Comment by simo5** [comment]
You are talking about CyrusIMAP, but this is about CyrusSASL offering interfaces.

The only issue we can handle here is that libsasl2 needs to be able to offer GSSAPI with CBs and without CBs, without requiring the use of a new name by clients (GSSAPI-PLUS).

One way to do that could be to provide an additional indication to plugins, or some other mechanism.
What we can't do is just blindly revert this support, as it is necessary to make the client library work against an important target.

**Comment by dilyanpalauzov** [comment]
How shall the libsasl2 API be used, in order for the application-server to offer the five mechanisms at the same time: SCRAM-SHA-1, SCRAM-SHA-1-PLUS, RFC-4752-compatible-GSSAPI , GS2-KRB5 and GS2-KRB5-PLUS?

**Comment by simo5** [comment]
That's the question we need to answer, it seem to me that the problem is that providing CBs is not a sufficient signal, and that an additional indication of whether they should be used should be provided.
In the case of GSSAPI the indication should be the CBS should not be required.

**Comment by iboukris** [comment]
CC @hyc & @quanah.

**Comment by hyc** [comment]
Sounds like we should add a new secprop for enabling CBs. Or even (ugly) one specifically to enable in the current GSSAPI plugin.

**Comment by Neustradamus** [comment]
@aamelnikov, @ksmurchison: Can you look it?
