### ISSUE TITLE
SCRAM: Exception when server does not support channel binding

### ISSUE THREAD

**Issue by GuidoKiener** [cyrusimap/cyrus-sasl#641]
Hi,

during tests with a new protocol (HiSLIP2) for T&M instruments, I found the following bug in the SCRAM plugin.

When the server does not support channel binding, but the client requires channel binding with the SCRAM_CB_FLAG_P, then the server crashes in step 2 with an exception in strcmp(sparams->cbinding->name, ...)

You can find a patch here: [f535740](https://github.com/GuidoKiener/cyrus-sasl/commit/f5357406659623ee62dfc2c7b6c31194efacb257)
Or when this patch is ok, I can submit a pull request.

-Guido

**Comment by quanah** [comment]
Please submit your patch as a pull request so it can be reviewed, thanks!

**Comment by Neustradamus** [comment]
Thanks @GuidoKiener!

Linked to:
- https://github.com/cyrusimap/cyrus-sasl/pull/654

**Comment by quanah** [comment]
closed via 253f3f4ef025cacfaf86f90431cf977ca4659fa1
