### ISSUE TITLE
Kafka Consumer GSSAPI Error on alpine container, but works on Fedora

### ISSUE THREAD

**Issue by Hubbitus** [cyrusimap/cyrus-sasl#649]
Hello.

I've detailed describe issue [in kafkacat tracker](https://github.com/edenhill/kafkacat/issues/319), but it's closed as cyrus-sasl/krb5 issue. Please take a look at https://github.com/edenhill/kafkacat/issues/319

In two words - kafkacat on Fedora works, but on alpine container cyrus-sasl reported no matching credentials.

**Comment by Hubbitus** [comment]
Very strange issue, and honestly I can't say why, but adding into `krb5.conf`:

```
[libdefaults]
dns_canonicalize_hostname = false
```
solves the problem.

P.S. I've posted that as the solution because it starts work. But if someone may explain in comments why it is the solution and especially how that may be understandable from provided logs it will be very helpful.

**Comment by quanah** [comment]
This also does not appear to be a SASL issue, but an environment/DNS issue.
