### ISSUE TITLE
Des/Rc4 implementation in digestmd5 and deprecations.

### ISSUE THREAD

**Issue by simo5** [cyrusimap/cyrus-sasl#665]
digestmd5 defined 3 possible choices for rc4: rc4-40, rc4-56 and rc4, however as far as I can tell they all end up using the same functions which are not parametric (the functions only implement the full strength RC4).

Additionally there is a full custom re-implementation of RC4 in the file in addition to the code calling openssl.

On the DES side digestmd5 still defines des and 3des as options.
Here there are also 2 implementations, custom and openssl basedof des, on which 3des is constructed.

All this is old cruft that is cryptographically quite broken.

Proposal:
- remove the custom implementations and always depend on openssl's legacy provider.
- drop the rc4-40,rc4-56 defintions as they are useless.
- drop support for classic des and declare 3des deprecated.

Finally declare the whole module deprecated, and prepare for dropping it in some future release.

**Comment by quanah** [comment]
Probably declare as deprecated in 2.1.28, remove in 2.2

**Comment by simo5** [comment]
is it ok to drop the custom implementations in 2.1.28 and always rely on openssl ?

**Comment by quanah** [comment]
@hyc thoughts on @simo5 question? :)

**Comment by hyc** [comment]
Alll of that sounds good to me. There's no good reason to keep a homegrown crypto implementation, especially when we already depend on OpenSSL.

**Comment by hyc** [comment]
As usual for deprecating/removing something like digestmd5, the replacement (SCRAM) should be in wide use before the actual deletion/removal.

**Comment by simo5** [comment]
agreed!
I have some patches almost ready, will open a PR, it is a follow up of my latest one to enable building on openssl3

**Comment by Neustradamus** [comment]
@quanah, @hyc: What do you think?
It will be good before the 2.1.28 release?

**Comment by bgermann** [comment]
This should be removed from the 2.2.0 milestone in favor of #751.

**Comment by bgermann** [comment]
As far as I can see, the whole module was deprecated with b85268ec0f1ace84b83b45cf8385f978da0c19cc which was released with 2.1.27. So why should it not be removed in 2.2 as RFC6331 also declared it historic?

**Comment by bgermann** [comment]
The removal is implemented with  #773.

**Comment by quanah** [comment]
You can't use DES or 3DES with OpenSSL 1.1 and later unless it's built to allow deprecated functions.  3DES is marked *must not use* at the end of this year, less than 6 months away.  At this point I'm generally inclined to say digest-md5 gets dropped in 2.1.29 as well, unless someone implements AES for it.

**Comment by quanah** [comment]
> @ all : Little question, it is not possible to remove CRAM-MD5 at the same time?
> 
>     * https://datatracker.ietf.org/doc/html/draft-ietf-sasl-crammd5-to-historic-00
> 
>     * https://datatracker.ietf.org/doc/html/draft-zeilenga-luis140219-crammd5-to-historic-00

File a new issue for it, thanks!
