### ISSUE TITLE
Cyrus SASL 2.1.28 Testing Call

### ISSUE THREAD

**Issue by sfhacker** [cyrusimap/cyrus-sasl#697]
**Environment**

- Windows 10 x64

	
**Toolchain**

- GCC 11.1.0 x64

	
**Build Options**

- OpenSSL 1.1.1l
- Heimdal Kerberos
- LMDB

- Static Plugins

	
We are in the process of testing several mechanisms (e.g. GSSAPI) at the moment.
Will update this issue regularly.

Thanks for this milestone!

**Screenshots**

![image](https://user-images.githubusercontent.com/25817529/143005008-12742983-962e-4547-b0b0-f84bc6513900.png)

**Comment by quanah** [comment]
2.1.28 released, closing
