### ISSUE TITLE
Custom license for auth_pam

### ISSUE THREAD

**Issue by bgermann** [cyrusimap/cyrus-sasl#698]
saslauthd/auth_pam.[ch] files are licensed under a BSD-2-clause similar license with the 2nd clause showing up twice with a minor difference in the wording. The files should be converted to a standard license.

**Comment by bgermann** [comment]
@fknittel I guess you are the copyright holder. Would you be okay with relicensing cyrus-sasl's files saslauthd/auth_pam.c and saslauthd/auth_pam.h to the [standard BSD-2-Clause](https://spdx.org/licenses/BSD-2-Clause.html)?

**Comment by fknittel** [comment]
Sure, relicensing to Standard BSD-2-Clause would be absolutely fine with me.

**Comment by fknittel** [comment]
... and yes, I wrote that piece of code and no I'm not sure from why it's not under standard BSD-2-Clause already. Might have mistakenly copy & pasted from somewhere.
