### ISSUE TITLE
sasl_client_new() should not query DNS for client hostnames

### ISSUE THREAD

**Issue by ktdreyer** [cyrusimap/cyrus-sasl#700]
When I use ANONYMOUS authentication to a service (eg AMQP), Cyrus looks up my client's hostname in DNS. It tries to look up my unqualified shortname in DNS. Not only is this unnecessary, but in my particular test environment, this can take several seconds for DNS to respond to both the A and AAAA queries for the unqualified name.

### Steps to reproduce:

1. Set up a CentOS 8 or 9 host.
2. Install cyrus-sasl-devel
3. Ensure the unqualified (short) hostname from the `hostname` command is not present in `/etc/hosts`.
4. Run the following program that simply calls `sasl_client_new()`:
```c
#include <stdio.h>
#include <sasl/sasl.h>

int main() {
   int result;

   result = sasl_client_init(NULL);
   if (result != SASL_OK) {
       printf("sasl failure:\n");
       printf("%s\n", sasl_errstring(result, NULL, NULL));
   }

    sasl_conn_t *conn;

    result = sasl_client_new("amqp",
                             "localhost",
                             NULL, NULL, /* Local and remote IP address
                                            strings (NULL disables mechanisms
                                            which require this info)*/
                             NULL,       /* connection-specific callbacks */
                             0,          /* security flags */
                             &conn);     /* allocated on success */

    if (result != SASL_OK) {
        printf("sasl failure:\n");
        printf("%s\n", sasl_errstring(result, NULL, NULL));
    }
}
```

### Actual results:
The program makes two DNS queries (A and AAAA) for my host's unqualified hostname. The AAAA request takes a while to answer (3.5 seconds) in my environment.

### Expected Results:
There should be zero DNS traffic for my client's hostname.

**Comment by ktdreyer** [comment]
I found this bug because the qpid-proton library behaves differently if it's compiled with cyrus-sasl or not. https://issues.apache.org/jira/browse/PROTON-2474 has the details. When I compile proton with cyrus-sasl, then Proton makes these DNS requests, and when I use proton's default SASL implementation, it does not use DNS.

**Comment by hyc** [comment]
`sasl_client_new()` calls `get_fqhostname()` unconditionally, regardless of which authentication mechanism will be used. In fact it doesn't know which mech is being used, that doesn't get determined until `sasl_client_start()`. Not sure it's worth the complexity of moving this initialization out of _new and into _start.

**Comment by hyc** [comment]
... but a `git grep` doesn't turn up any plugins that actually use the clientFQDN. Perhaps we should delete the relevant code for it.

**Comment by ktdreyer** [comment]
I noticed an additional "Step to reproduce". You need to set the hostname of the system to a name that has no dots "`.`". In other words, this will trigger the DNS lookup:
```
hostnamectl set-hostname kojidev
```
And this will not:
```
hostnamectl set-hostname kojidev.ktdreyer.com
```

It's because `get_fqhostname()` only falls through to the DNS query code `if (strchr (name, '.') != NULL)`.
