### ISSUE TITLE
tag for 2.1.28

### ISSUE THREAD

**Issue by tormath1** [cyrusimap/cyrus-sasl#704]
Hello,

It seems the release 2.1.28 is out - but there is no release tag for it: https://github.com/cyrusimap/cyrus-sasl/tags. Is that done on purpose ?

For example, Gentoo package is based on this archive: https://github.com/gentoo/gentoo/blob/master/dev-libs/cyrus-sasl/cyrus-sasl-2.1.27-r6.ebuild#L13

Thanks :)

**Comment by quanah** [comment]
There is no 2.1.28 release, what makes you believe it is released?

**Comment by tormath1** [comment]
Hi, thanks for answering !

It's maybe unclear but there are this two commits:
* https://github.com/cyrusimap/cyrus-sasl/commit/02cd70f706b3ff4220e0960636080c3b387e1a1c
* https://github.com/cyrusimap/cyrus-sasl/commit/3543c6dc46188f70029737367aed157a7e19f6e6

and also the documentation: https://www.cyrusimap.org/sasl/
> The latest stable version of Cyrus SASL is 2.1.28.

Sorry if there is a misunderstanding. :)

**Comment by quanah** [comment]
Those two commits are preparing for a release.  I don't know why the documentation updated to say 2.1.28, that seems to be a process error.  Until there's a listed release at https://github.com/cyrusimap/cyrus-sasl/releases it's not released.

**Comment by Neustradamus** [comment]
Dear all,

Latest Cyrus-SASL is 2.1.28 (2022-02-22), soon 3 years.

Can you go here for talk about a new version before Debian 13 freeze soon?

Next Debian 14 will be in 2027:
- https://github.com/cyrusimap/cyrus-sasl/issues/835

Thanks in advance.
