### ISSUE TITLE
client_dispose is not thread safe

### ISSUE THREAD

**Issue by quanah** [cyrusimap/cyrus-sasl#715]
Description from a Redhat patch.  Code in upstream cyrus-sasl remains unchanged.  Unclear why this was not submitted to upstream (or maybe it was and got lost?)

Description: client_dispose (lib/clinet.c) which closes a connection
of a sasl client frees mech_list if the head of the list differs
from the head of the global cmechlist->mech_list.  But there was a
possibility that the list appears in the middle of the global mech
list.  By freeing the mech, it crashed a multi-threaded sasl client.

**Comment by quanah** [comment]
See also https://git.centos.org/rpms/cyrus-sasl/raw/c7/f/SOURCES/cyrus-sasl-2.1.26-make-client-thread-sage.patch

**Comment by simo5** [comment]
I'll pull the new RH maintainer on this one.

**Comment by hyc** [comment]
Hey thanks @simo5 but not necessary. Sorry I didn't see your comment till now.
