### ISSUE TITLE
Remove support for BerkeleyDB as a backend

### ISSUE THREAD

**Issue by quanah** [cyrusimap/cyrus-sasl#718]
Since BDB now has an incompatible license, remove support as a storage backend.  Plenty of other options that are license compatible exist.

**Comment by winner658** [comment]
If BerkeleyDB is deleted, what products can be replaced? How to configure the products?

**Comment by quanah** [comment]
There are multiple choices, LMDB is the general suggested replacement for BDB

**Comment by hyc** [comment]
This commit broke auto_detect of the sasldb library.
