### ISSUE TITLE
mailing list seems to have disappeared

### ISSUE THREAD

**Issue by covici** [cyrusimap/cyrus-sasl#728]
In the readme.md it talks about a mailist at lists.andrew.cmu.edu but that list seems to have disappeared, I looked through the advertised lists there and its not there, so how can people get in touch?  Should I just open an issue here?

Thanks.

**Comment by hyc** [comment]
The new list is https://cyrus.topicbox.com/groups/info

I suppose we can treat this issue as a request to update the readme.
