### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by kloczek** [cyrusimap/cyrus-sasl#729]
Looking on https://github.com/cyrusimap/cyrus-sasl/compare/cyrus-sasl-2.1.28...master I thing that it is already enough accumulated to make new release.
Any plans to do that soon? 😋

**Comment by hyc** [comment]
That list of commits is bogus, it includes many commits previously released in 2.1.26, 2.1.27, and 2.1.28.

The next release will be 2.2.0, the number of deprecated/dropped mechanisms is too significant to be another 2.1 release.

**Comment by kloczek** [comment]
So it may take a bit longer. Am I right?
If yes still I think that it would be good to add in 2.1 branch for example openssl 3.x parches and push that as 2.1.29. 
Many distributions have own accumulated patches against latest 2.1. IMO it wold be good to review that, commit and include in next 2.1.x release. If you wan I can try to propose few PRS against 2.1 branch. IMO definitely for example it would be good to add systemd service description file.

**Comment by quanah** [comment]
There are no plans for a new 2.1 release. 2.2.0 is the next planned release series.

**Comment by Neustradamus** [comment]
Dear all,

Latest Cyrus-SASL is 2.1.28 (2022-02-22), soon 3 years.

Can you go here for talk about a new version before Debian 13 freeze soon?

Next Debian 14 will be in 2027:
- https://github.com/cyrusimap/cyrus-sasl/issues/835

Thanks in advance.
