### ISSUE TITLE
Help wanted: investigate developing an OPAQUE plugin

### ISSUE THREAD

**Issue by hyc** [cyrusimap/cyrus-sasl#741]
https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-opaque seems to be the successor to SRP these days.

**Comment by dequbed** [comment]
Hi!

I just stumbled upon this issue and wanted to link to a different one I made for the same reason: https://github.com/stef/libopaque/issues/31

I think combining effords here would benefit us all ^^

**Comment by stef** [comment]
there is already a cyrus-sasl mechanism doing opaque here: https://github.com/stef/libopaque/tree/master/sasl
and i also have a draft spec for it here https://github.com/stef/sasl-opaque

**Comment by stef** [comment]
> Thanks, will try it with OpenLDAP. 
> Would you consider contributing it to the cyrus-sasl project?
sure it should integrate easily, i built it as an OOT module, by copying out the internal functions i used from cyrus-sasl and put it all into https://github.com/stef/libopaque/blob/master/sasl/utils.c. all tests i build were based on cyrus-sasl, so it should work ootb

**Comment by stef** [comment]
one caveat there is no security layer.

**Comment by quanah** [comment]
Fixed by #756

**Comment by quanah** [comment]
Note: When working with github, if you include Fixes #ISSUE in your commits it will automatically close the issue when the PR is merged
