### ISSUE TITLE
sample test use gssapi reported error all the time

### ISSUE THREAD

**Issue by winner658** [cyrusimap/cyrus-sasl#743]
this is my sample conf:
![image](https://user-images.githubusercontent.com/14918864/184774739-3a957a38-12cf-4680-831a-470aa0abc68f.png)
when I user plain、login 、ntlm mech do test is ok, but use gssapi reported error all the time:
![image](https://user-images.githubusercontent.com/14918864/184778629-122db586-9326-4a34-8a9f-c421d451f524.png)

but I have krb5 server and had created user account :
![Uploading image.png…]()

so What should I do now?

**Comment by quanah** [comment]
I would suggest asking on the email forums: https://cyrus.topicbox.com/groups/sasl
