### ISSUE TITLE
runtests.py ：The return value of the  gssapi_channel_binding_mismatch_test() function is incorrect.

### ISSUE THREAD

**Issue by winner658** [cyrusimap/cyrus-sasl#746]
in tests/runtests.py file，when the gssapi_channel_binding_mismatch_test() runs normally and is bound successfully, the gssapi_channel_binding_mismatch_test() returns an incorrect result value instead of a correct result value. When an exception occurs, the gssapi_channel_binding_mismatch_test() returns a correct result value. As a result, the following error message is displayed after all tests are passed in time:
![image](https://user-images.githubusercontent.com/14918864/187192919-fc7798da-88e9-407f-bb83-39fa22ef1f48.png)
 
in other function: the return value is 0 for success and 1 for exception.
![image](https://user-images.githubusercontent.com/14918864/187192975-a7aff770-0831-4058-bd96-cd7e7a4f593b.png)

**Comment by hyc** [comment]
I don't believe your assessment is correct. The test clearly says "This test should fail" which means a successful bind is a failure, not a success.
