### ISSUE TITLE
gssapi.c:resolve_ccache_store() could read free()ed data

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-sasl#749]
plugins/gssapi.c:resolve_ccache_store() has this logic for ccache_copy:
```c
 char* ccache_copy = NULL;
 ccache_copy = strdup(ccache)
 while (NULL != (needle = strchr(ccache_copy, '%'))) {
   …
   free(ccache_copy);
   if (NULL != ccname) {
      ccache_copy = strdup(ccname);
      if (NULL == ccache_copy) {
         text->utils->seterror(text->utils->conn, SASL_LOG_ERR, "GSSAPI error: out of memory");
         goto malloc_failed;
      }
    }
}
```
When on the second last `if` ccname is `NULL`, the `while` condition at the top is executed.  There the memory of `ccache_copy` is read, despite being deallocated in the previous loop iteration.

This might in theory never happen, I have not followed the procedure’s logic in detail.  But in case it does not happen, `free(ccache_copy);` shall be within `if (NULL != ccname)`.

**Comment by hyc** [comment]
Can never happen. Every valid case of the switch statement will populate ccname, and every invalid case and the default case will `goto parsing_failed`.
