### ISSUE TITLE
how to use httpform

### ISSUE THREAD

**Issue by eosps** [cyrusimap/cyrus-sasl#760]
I can't find anything online about configuring httpform. Who can provide how to configure it. Thanks

**Comment by hyc** [comment]
That mech was written in 2006 and no doc was ever provided. You'll have to read auth_httpform.c to see how it works. In particular, you can find the 4 config settings it expects here https://github.com/cyrusimap/cyrus-sasl/blob/master/saslauthd/auth_httpform.c#L435  

set them in the saslauthd config file.
