### ISSUE TITLE
OpenLDAP passthrough not working with SASL Cyrus

### ISSUE THREAD

**Issue by smanikkara** [cyrusimap/cyrus-sasl#761]
Hi team

I integrated pass through ldap authentication to external AD
testsaslauthd -u smanikka@mail.com  -p  ***ADpassword***** -f /var/run/saslauthd/mux
0: OK "Success."

From OpenLDAP server its giving proper out put
But from outside ldap search against openldap with AD password getting "invalid credentials " error

It seems {SASL}user@domain in uderPassword field not accepting in my Openldap server
Do you have any suggestions to make it work

**Comment by quanah** [comment]
I suggest not using SASL passthrough at all.  If you're on a modern version of OpenLDAP, use the remotauth overlay instead.

**Comment by smanikkara** [comment]
Thanks for the reply
Is there any document to implement  remoteauth overlay in already built OpenLDAP server (using yum install)

**Comment by quanah** [comment]
> Thanks for the reply Is there any document to implement remoteauth overlay in already built OpenLDAP server (using yum install)

Generally I'd suggest moving this discussion to the openldap-technical mailing list.  The remoteauth overlay is a standard overlay with OpenLDAP 2.5 or later, and there is a man page for it.
