### ISSUE TITLE
Cyrus-sasl-2.1.29 release

### ISSUE THREAD

**Issue by kloczek** [cyrusimap/cyrus-sasl#762]
https://github.com/cyrusimap/cyrus-sasl/compare/cyrus-sasl-2.1.28...master shows +190 commits since last release which was +year ago.
Any plans to release new version? 🤔

**Comment by quanah** [comment]
master is work on cyrus-sasl 2.2, there is no timeline on that release.  We are discussing a 2.1.29 release purely for ensuring openssl 3 compatibility as OpenSSL 1.1.1 series is being retired by the OpenSSL project.

**Comment by kloczek** [comment]
Thank you 👍

**Comment by bgermann** [comment]
When will the release happen? All milestone issues are done.

**Comment by quanah** [comment]
> When will the release happen? All milestone issues are done.

DIGEST-MD5 needs removal since there's no way to support it with OpenSSL3.

**Comment by bgermann** [comment]
Really? The MD5 implementation in 2.1 is the internal one. RC4 was removed. That leaves us with DES and 3DES. For DES, one has to use the legacy provider but I think you can certainly use 3DES.

**Comment by bgermann** [comment]
For a stable version update, mechanism removal is a bit tough for my taste.

**Comment by bgermann** [comment]
I see: The des.h functions are deprecated. Would it be an alternative to port to evp.h?

**Comment by hyc** [comment]
We didn't feel like any porting effort was justified for something we're about to delete.

**Comment by bgermann** [comment]
If the OpenSSL installation does not have DES_cbc_encrypt the DIGEST-MD5 will still compile but without any available method. I think this is good enough and it will not break on  modern configurations.

In this problem space, e4a9a7e2360aa7dbc90c6907021819bf99799265 would be a much better backport candidate because srp compilation is broken on OpenSSL without legacy APIs.

**Comment by hyc** [comment]
Not sure what the point of including it is then, if it has no security layer. Better to just remove it so admins have to recognize that they need to choose a new mech.

**Comment by bgermann** [comment]
The point of including is that OpenSSL 3.0 can be configured to retain the legacy APIs and in Debian, it will be like that for the forseeable future. I do not think I am going to upgrade Debian's cyrus-sasl2 to 2.1.29 if DIGEST-MD5 will be dropped. In that case I am going to wait with an update to 2.2 (most likely after the next Debian release trixie). Everyone who wants to get rid of the mechanism can do so by disabling it.

**Comment by quanah** [comment]
The only purpose for 2.1.29 at this time is for a release that can use OpenSSL 3.0 when there deprecated APIs are not enabled.  No distro should be updating to 2.1.29.

**Comment by alls0rts** [comment]
Several distributions have backported the master branch OpenSSL 3 changes to version 2.1.27 and 2.1.28.
Having an official 2.1 branch would be preferable.

**Comment by quanah** [comment]
> Several distributions have backported the master branch OpenSSL 3 changes to version 2.1.27 and 2.1.28. Having an official 2.1 branch would be preferable.

Several distributions took changes from a PR that was not accepted upstream and added them to their builds without consultation with the cyrus-sasl development team.

**Comment by alls0rts** [comment]
> > Several distributions have backported the master branch OpenSSL 3 changes to version 2.1.27 and 2.1.28. Having an official 2.1 branch would be preferable.
> 
> Several distributions took changes from a PR that was not accepted upstream and added them to their builds without consultation with the cyrus-sasl development team.

This thread....
[quanah commented on May 24, 2022](https://github.com/cyrusimap/cyrus-sasl/issues/729#issuecomment-1136115369)
> There are no plans for a new 2.1 release. 2.2.0 is the next planned release series.

**Comment by mistotebe** [comment]
Please enlighten me, but the only thing I hear being mentioned is the ciphers needed for confidentiality/integrity support (security layers), but all the `qop` stuff is optional in the RFC.

So if we pull support for `qop`, I don't see why OpenSSL 3 has any bearing on this and should prevent DIGEST-MD5 from staying in 2.1? Is there anything else?

**Comment by hyc** [comment]
Those security layers are enabled by default. Most installations using DIGEST-MD5 expect them to be there. Turning them off usually means the mech is ineligible for use (based on configured secprops) and so the mech would effectively disappear/be disabled anyway. What's the point of keeping it then?

**Comment by mistotebe** [comment]
Except that's the only thing we can't actually deliver any more. Those connections you're talking about would be coming in over plaintext for `qop=auth-int` or `qop=auth-conf` to have a point in the first place. `qop=auth` (the default) is still there and the only secprops that look like they would disable DIGEST-MD5 based on this is `minssf`.

**Comment by hyc** [comment]
We (Symas) are having a conference call next week on Monday at 4:30pm GMT to discuss how to proceed. Anyone with an interest in the question can join in using the call-in numbers listed here https://www.symas.com/about-symas to reach extension 76029, no PIN.

**Comment by alls0rts** [comment]
> We (Symas) are having a conference call next week on Monday
Thanks @hyc .  To be clear and open.  On Solaris 11.4 SRU, where
SSL 1.1.1 has already been removed, cyrus-sasl 2.1.28 is currently
being linked with latest SSL 1.0.2.   We intend to switch to SSL
3.0 (using patches to 2.1.28) when ready (several other packages
rely on cyrus-sasl and thus need to be switched at the same time).

As such Solaris can skip 2.1.29 (as suggested by @quanah) and look
towards 2.2 in the near future.

**Comment by mistotebe** [comment]
There is still no indication what the outcome of the mentioned call was. From other communication I presume something along the lines that there will be no more releases in the 2.1 stream, instead aiming to release 2.2 at some point.

**Comment by kloczek** [comment]
Why this ticket has been closed if still thee is no new release? 🤔

**Comment by quanah** [comment]
There will be no new releases of the 2.1 series. This ticket was about 2.1.29, there won't be one.

**Comment by Neustradamus** [comment]
Dear all,

Latest Cyrus-SASL is 2.1.28 (2022-02-22), soon 3 years.

Can you go here for talk about a new version before Debian 13 freeze soon?

Next Debian 14 will be in 2027:
- https://github.com/cyrusimap/cyrus-sasl/issues/835

Thanks in advance.

**Comment by mistotebe** [comment]
@Neustradamus please stop commenting on every bug report you find, @ mentioning the world etc. It is only going to be seen as spam as countless other projects have told you already and taken together it can be seen as harassment. This is a community project maintained on a volunteer basis, if you want things done (sooner) you have two options: you can step in and help make it happen or you can hire someone to work on whatever you consider a priority.

Right now you are doing neither, on the contrary, your endless stream of comments on random (and mostly closed?) tickets without even engaging in a discussion is taking away from, not contributing to, this project.

Consider this your final warning: if you continue this behaviour, you **will** be blocked.
