### ISSUE TITLE
Get rid of RSA-MD license

### ISSUE THREAD

**Issue by bgermann** [cyrusimap/cyrus-sasl#769]
As explained in dffe0b3e86925c95e6f30ec0f2de9fb0c439c7bc, the RSA-MD-licensed file md5.c can be relicensed easily because the third-party code that was licensed under RSA-MD is eliminated by now. The relicensing should happen because RSA-MD is known to be GPL-incompatible.

**Comment by rlaager** [comment]
Can we agree that this issue is limited to "Rob Earhart made changes to the code that are possibly copyrightable"?

If so, I will engage further on that, to refine the scope further.

**Comment by bgermann** [comment]
Yes.

**Comment by bgermann** [comment]
Agreed.

**Comment by rlaager** [comment]
Well, it turns out that second level of analysis was not necessary, as Rob responded. So that was easy!
