### ISSUE TITLE
Opaque module introduces an error with configure

### ISSUE THREAD

**Issue by bgermann** [cyrusimap/cyrus-sasl#781]
configure: error: conditional "OPAQUE_INTERNAL" was never defined.

**Comment by quanah** [comment]
Just to confirm, you regenerated configure from configure.ac after the opaque work was added

**Comment by bgermann** [comment]
Yes, I have regenerated 'configure'. The error appears even with `--disable-opaque` when the libopaque and libsodium checks fail.

**Comment by quanah** [comment]
Ok, thanks! I'll dig into this on Monday, I'm guessing that it wasn't tested when the requirements for opaque were not available.
