### ISSUE TITLE
Remove historic CRAM-MD5 mechanism

### ISSUE THREAD

**Issue by Neustradamus** [cyrusimap/cyrus-sasl#787]
Dear @cyrusimap team,

It is not possible to remove CRAM-MD5 at the same time than DIGEST-MD5:
- https://datatracker.ietf.org/doc/html/draft-ietf-sasl-crammd5-to-historic-00
- https://datatracker.ietf.org/doc/html/draft-zeilenga-luis140219-crammd5-to-historic-00

Thanks in advance.

**Comment by Neustradamus** [comment]
@quanah: Do not forget cyrus-imapd:
- https://github.com/search?q=repo%3Acyrusimap%2Fcyrus-imapd+CRAM-MD5&type=code
- https://github.com/search?q=repo%3Acyrusimap%2Fcyrus-imapd+DIGEST-MD5&type=code

**Comment by quanah** [comment]
You should file a ticket with the cyrus-imap team so they can handle it.

**Comment by Neustradamus** [comment]
@quanah: Thanks, it is done! :)
