### ISSUE TITLE
[Windows] Test suite segmentation fault

### ISSUE THREAD

**Issue by sfhacker** [cyrusimap/cyrus-sasl#790]
Ciao.

OS   : Windows
ARCH : x86_64

SASL Version: master branch
SASL DB       : LMDB / Static

When running testsuite file, an exception is thrown:

![image](https://github.com/cyrusimap/cyrus-sasl/assets/25817529/5f37bddb-b47e-446e-adf6-5ab267703832)

This project seems to be in bad shape. We have also faced some compilation issues regarding this file: kdf_hkdf_sha512 among other issues.

Is there any CI server in place? Perhaps that can help.

Thanks in advance.

**Comment by quanah** [comment]
Master is under significant churn in preparation for cyrus-sasl 2.2.  I would note that the test suite issues are not limited to master, see #758

**Comment by alls0rts** [comment]
I have run into this as well, it's a simple fix.  I shall create a pull request.
