### ISSUE TITLE
Can saslpasswd2 be run as non-root user? 

### ISSUE THREAD

**Issue by arunlalkm-intel** [cyrusimap/cyrus-sasl#797]
saslauthd -a pam is how I am running the saslauthd executable and this is running as root. 

I would like a non-root application to call saslauthd to authenticate password. This I tested by running testsaslauthd as non-root and that worked.

Now I need to make sure my non-root user can change the password. And I see for this I need to use saslpasswd2. So my question is can saslpasswd2 be run as non root? 
Or is there a better approach?

**Comment by hyc** [comment]
saslpasswd2 is only used for operating on sasldb. `saslauthd -a pam` doesn't use sasldb, so this is irrelevant.
