### ISSUE TITLE
[PLUGIN][OPAQUE] Unable to make it work

### ISSUE THREAD

**Issue by sfhacker** [cyrusimap/cyrus-sasl#810]
Hi.

OS: Windows 10 x64
Branch: master
libsodium: 1.0.19

First time testing this plugin so ... bear with me.

**Server side**

![image](https://github.com/cyrusimap/cyrus-sasl/assets/25817529/faefe463-965f-4101-9e63-c88340b47b6f)

**Client side**

![image](https://github.com/cyrusimap/cyrus-sasl/assets/25817529/536d943d-b16e-41c7-8c45-bd34fe42db64)

Any pointers how to properly test this plugin?

Thanks a lot.

**Comment by hyc** [comment]
I see the same failure on Linux using sample-client and sample-server. However, using `sample/client` and `sample/server` works fine.
