### ISSUE TITLE
Add a way to configure the build to embed (only some ?) plugins into the main libsasl2.a/libsasl2.so

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [cyrusimap/cyrus-sasl#837]
Hi,

We are hitting a small issue with libsasl2 as it comes with a plugin mechanism which is a bit incompatible with how we build/deliver/deploy software. Usually we expect a lib to be kind like a "normal" library: either autonomous, either depending on other "normal" libraries and having the expected ELF DT_NEEDED dependencies (or whatever equivalent at build system level to describe a dependency). Libraries coming with the concept of plugins like libsasl2, which  "auto-discovers" at runtime which plugins are available by opening a built-time hardcoded default plugin folder aren't ideal, as the dependencies are more runtime one, and don't really accept libraries to be just in LD_LIBRARY_PATH like other "normal" libraries.

All the other open source libraries we use and which have a similar plugin concept (for example OpenSSL with dynamic engine loading, or the mariadb c-connector with different authentication mechanism) all have a build-time option to actually embed the .o files of the plugins directly into the final lib .a or .so file. I didn't find such a way to configure libsasl2. Would it make sense to add such an option (of course, disable by default to keep the existing behavior) ? This way libsasl2.so would be a "normal" library, potentially depending on things like kerberos runtime libraries, without addition plugin runtime dependencies.

Thanks

**Comment by hyc** [comment]
That's what `--with-staticsasl` does.

**Comment by Romain-Geissler-1A** [comment]
Hi @hyc,

I have changed a bit the title of this request and added an EDIT section in my request following your reply. Is this request valid with the re-phrased requirements ?

**Comment by Romain-Geissler-1A** [comment]
Ping @hyc
