### ISSUE TITLE
Leak in gssapi_client_mech_step

### ISSUE THREAD

**Issue by BlakeIsBlake** [cyrusimap/cyrus-sasl#843]
If `HAVE_GSS_KRB5_CRED_NO_CI_FLAGS_X` is true, we will [acquire credentials from kerberos](https://github.com/cyrusimap/cyrus-sasl/blob/bd9146c25e3a6de45112b06b9f6ba8c81d0f9bd9/plugins/gssapi.c#L2179-L2182). There is no check if `&text->client_creds` already has a value, and so it's possible to overwrite the existing value, and leak the previous value of `&text->client_creds`.

On the server side, we [check](https://github.com/cyrusimap/cyrus-sasl/blob/bd9146c25e3a6de45112b06b9f6ba8c81d0f9bd9/plugins/gssapi.c#L1182-L1187) if `server_creds` already exists so that we release the memory before reassigning. We could do something similar on the client side to avoid a leak.

Note that those using this library are currently affected by this issue can use a local compile with the `HAVE_GSS_KRB5_CRED_NO_CI_FLAGS_X` flag disabled to avoid the leak until the underlying issue is resolved.

**Comment by hyc** [comment]
`text->client_creds` comes from `params->gss_creds`

https://github.com/cyrusimap/cyrus-sasl/blob/bd9146c25e3a6de45112b06b9f6ba8c81d0f9bd9/plugins/gssapi.c#L2041

The code you reference only executes if `params->gss_creds == GSS_C_NO_CREDENTIAL`

https://github.com/cyrusimap/cyrus-sasl/blob/bd9146c25e3a6de45112b06b9f6ba8c81d0f9bd9/plugins/gssapi.c#L2170

So how can there already be an existing value in `text->client_creds`?

**Comment by BlakeIsBlake** [comment]
I am not 100% sure, but it does happen -- I have an in-house ASAN repro that triggers a leak every time. I'll see if I can't get you an answer to your question today, or genericize the repro to post here.

**Comment by BlakeIsBlake** [comment]
`text_client_creds` actually comes from `gss_acquire_cred`. We assign to a local variable `client_cred` but never back to `params`, so `client_cred` doesn't outlive `gssapi_client_mech_step`. Am I missing something else here?

**Comment by BlakeIsBlake** [comment]
These last two assertions fail, but the first succeeds:

```
client_creds = text->client_creds;
assert(client_creds != GSS_C_NO_CREDENTIAL);
assert(client_creds == (gss_cred_id_t)params->gss_creds);
assert((gss_cred_id_t)params->gss_creds != GSS_C_NO_CREDENTIAL);
```

**Comment by hyc** [comment]
Since this is getting a Kerberos ticket within a single authentication attempt, it makes no sense for acquire_cred to be called more than once. I think the actual fix is to prevent that, not a simple leak fix.

**Comment by hyc** [comment]
But again, I don't see how this would get called twice, since `text->state` should have progressed to the next state after the first time through.

**Comment by hyc** [comment]
OK, so it's calling gss_acquire_cred redundantly, that's the actual bug. Though now I'm also wondering why gss_init_sec_context didn't complete the first time, can ignore that for now.

**Comment by BlakeIsBlake** [comment]
Confirmed your patch fixes the issue :)
