### ISSUE TITLE
“libsasl2 symbol versioning” commit breaks my build

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-sasl#847]
e24aefc98d07a2ece12c62282daf849713d52617 breaks my build with “utils/sasldblistusers.c:189: undefined reference to `sasl_global_utils'”.  With it:
```
make distclean && rm -rf autom4te.cache/ && ./autogen.sh && ./configure && make
…
make[2]: Entering directory '/git/cyrus/cyrus-sasl/utils'
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -Wall -W -Wall -Wextra -g -O2 -pthread -rpath /usr/local/lib  -o sasldblistusers2 sasldblistusers.o ../sasldb/libsasldb.la ../lib/libsasl2.la -llmdb  -lcrypto -lresolv -lgssapi_krb5 -lresolv -lpthread 
libtool: link: gcc -Wall -W -Wall -Wextra -g -O2 -o .libs/sasldblistusers2 sasldblistusers.o  ../sasldb/.libs/libsasldb.a ../lib/.libs/libsasl2.so -ldl -llmdb -lcrypto -lgssapi_krb5 -lresolv -lpthread -pthread -Wl,-rpath -Wl,/usr/local/lib
/usr/bin/ld: sasldblistusers.o: in function `main':
/git/cyrus/cyrus-sasl/utils/sasldblistusers.c:189:(.text.startup+0x169): undefined reference to `sasl_global_utils'
/usr/bin/ld: /git/cyrus/cyrus-sasl/utils/sasldblistusers.c:194:(.text.startup+0x186): undefined reference to `sasl_global_utils'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:667: sasldblistusers2] Error 1
```
… so sasl_global_utils is optimized out.

Without that commit it works.

I use gcc (GCC) 14.1.1 20240701 (Red Hat 14.1.1-7) and GNU ld version 2.41-37.fc40.

**Comment by hyc** [comment]
Now fixed in 332e8cd9b2f1fc46ece371cbd814bb32858adb4d

**Comment by mistotebe** [comment]
@dilyanpalauzov how do you get `sasldblistusers2` to compile? master compiled just fine for me given the procedure you outline (and out of the things in `utils/`, only `pluginviewer` is compiled)

**Comment by dilyanpalauzov** [comment]
utils/Makefile.am contains:
```
sbin_PROGRAMS = @SASL_DB_UTILS@ @SMTPTEST_PROGRAM@ pluginviewer
EXTRA_PROGRAMS = saslpasswd2 sasldblistusers2 testsuite testsuitestatic smtptest pluginviewer

sasldblistusers2_LDADD = ../sasldb/libsasldb.la $(all_sasl_libs)
sasldblistusers2_SOURCES = sasldblistusers.c
sasldblistusers2_LDFLAGS = -rpath $(libdir)
```
m4/sasldb.m4 sets `SASL_DB_UTILS="saslpasswd2\$(EXEEXT) sasldblistusers2\$(EXEEXT)"`.  Unless dblib is gdbm, lmdb or ndbm, this is changed to `SASL_DB_UTILS=""`.

When I call

> $ ../configure --disable-gssapi --enable-static --without-des

the output is
> checking for db.h... (cached) yes
> checking DB library to use... berkeley

So I guess dblib is set to berkeley and therefore SASL_DB_UTILS includes sasldblistusers2. (It is not very clear from my explanation what exactly happens, but I think if you have lmdb installed, then sasldblistusers2 should be compiled).
