### ISSUE TITLE
2.1.28: Issues with including time.h

### ISSUE THREAD

**Issue by dvzrv** [cyrusimap/cyrus-sasl#859]
Hi! :wave: 

Upon rebuilding the libsasl component for Arch Linux I noticed that we have issues with the (missing) inclusion of `time.h` now.

I believe the following should check for `HAVE_SYS_TIME_H` instead:
https://github.com/cyrusimap/cyrus-sasl/blob/537af16986caff73ef45ab54a5a020bfb636ddaf/lib/saslutil.c#L62-L64

This issue is also present in the (now deleted) plugins/cram.c.

I'll have to backport the fix for the deleted file now, but I can open a PR for the fixing of saslutil.c.
That said: A new release would be very good to have.

**Comment by dvzrv** [comment]
Argh... I just found that this has been fixed two years ago in https://github.com/cyrusimap/cyrus-sasl/commit/266f0acf7f5e029afbb3e263437039e50cd6c262

Please create a release! :pray:

**Comment by quanah** [comment]
There will be no more releases of the 2.1 series. Work on getting a 2.2 release out is ongoing.
